Synthetixio/synthetix

tests/test_EtherNomin.py
tests/test_Owned.py
utils/deployutils.py

Added a Dummy account, as well as a fresh_account() function for easier account management.

Account manager

---

contracts/Havven.sol
tests/contracts/PublicHavven.sol

Changes to Havven contract to store penultimate period start time

Havven contract fixes

---

contracts/Court.sol
contracts/Havven.sol
tests/contracts/PublicHavven.sol
tests/test_Havven.py

Removed mentions of court/voting in the havven contract, as havvens are no longer locked up.

removed votes and court from havven contract

---

contracts/Havven.sol
tests/__init__.py
tests/contracts/PublicHavven.sol
tests/test_EtherNomin.py
tests/test_FeeCollection.py
tests/test_Havven.py
utils/generalutils.py

Tests for fee withdrawal over multiple periods, with different percentages of havven being utilised

Fee withdrawal tests

---

contracts/EtherNomin.sol
tests/test_EtherNomin.py

Update the fee rate in line with Kain's wishes.

Updated fee rate from 20 basis points to 15.

---

.soliumignore
.soliumrc.json
contracts/Court.sol
contracts/EtherNomin.sol
contracts/Havven.sol
contracts/HavvenEscrow.sol
contracts/Owned.sol

* Added solium linting init files.
* Fixed some minor formatting issues in `Owned.sol`, `HavvenEscrow.sol`, `Havven.sol`.
* Improved naming and commenting, and slightly restructured `HavvenEscrow.addRegularVestingSchedule`.

Solium fixes

---

.travis.yml
README.md
requirements.txt
run_tests.py
utils/generalutils.py

- Travis CI runs the test suite now (with a build badge in the readme).
- `run_tests.py` runs ganache by itself now.
- Removed ganache error message which squelched other debug output after exceptions.

Travis Continuous Integration

---

contracts/Nomin.sol

Matches new state of affairs after launch of nUSD.

Updating description of contract.

---

contracts/NominAirdropper.sol
tests/__init__.py
tests/contract_interfaces/nomin_airdropper_interface.py
tests/test_NominAirdropper.py

Added Nomin Airdropper contract

---

contracts/ExternStateToken.sol
contracts/FeeToken.sol
contracts/Havven.sol
contracts/HavvenEscrow.sol
contracts/IssuanceController.sol
contracts/LimitedSetup.sol
contracts/Nomin.sol
contracts/NominAirdropper.sol
contracts/Owned.sol
contracts/Pausable.sol
contracts/Proxy.sol
contracts/Proxyable.sol
contracts/SafeDecimalMath.sol
contracts/SelfDestructible.sol
contracts/State.sol
run_tests.py
tests/contracts/PublicHavven.sol
tests/contracts/PublicNomin.sol
utils/deployutils.py

Solidity now has a feature where we can supply an explanation for why we're reverting a transaction. This PR adds descriptions to all of our require statements across the code base.

Added descriptions to all of our require() statements

---

contracts/ExternStateToken.sol
contracts/IssuanceController.sol
contracts/ReentrancyPreventer.sol
contracts/TokenRecipient.sol
tests/contract_interfaces/issuanceController_interface.py
tests/contracts/EmptyTokenRecipient.sol
tests/contracts/ReEntrantTokenRecipient.sol
tests/contracts/TokenRecipient.sol
tests/test_ExternStateToken.py
tests/test_FeeToken.py
tests/test_IssuanceController.py

Adds ETH -> HAV conversion in the issuance controller.

Issuance updates

---

contracts/FeePool.sol

Implemented gas optimisation as recommended by Sigma Prime. Left comment explaining what's up for future Synthetix team members.

Gas Optimisation: HBN-628

---

contracts/Depot.sol
migrations/2_deploy_synthetix_system.js
test/Depot.js

This PR fixes a number of linter errors that have crept in over time.

Fix Linter Errors

---

contracts/ExchangeRates.sol
contracts/Synthetix.sol
test/Synthetix.js

Also, gas optimisation on xdrParticipants.

Updated tests to ensure that the XDR synth can never be removed.

---

contracts/EscrowChecker.sol

Adding EscrowChecker contract

---

publish/index.js

Just a couple of minor changes - it needs a review to merge.

Minor updates to deploy script

---

contracts/FeePool.sol
test/FeePool.js

Also it was incorrectly calculated

remove exchangedAmountToReceive viewer func from FeePool as not used

---

contracts/ReentrancyPreventer.sol

ReentrancyPreventer to cost exactly 10K gas instead of 25K gas and 15K gas refund
Gas optimization PR according to GitCoin bounty: https://gitcoin.co/issue/Synthetixio/synthetix/196/3430

Optimize ReentrancyPreventer

---

contracts/Synth.sol

Reduce by 5k gas on each `transferFrom`
Gas optimization PR according to GitCoin bounty: https://gitcoin.co/issue/Synthetixio/synthetix/196/3430

Avoid setAllowance call in case of infinite allowance

---

contracts/Proxyable.sol

Gas diff (decrease font size in browser to fit in line): https://www.diffchecker.com/xpsXqgKK

Optimize optionalProxy modifier

---

contracts/ExchangeRates.sol
contracts/PurgeableSynth.sol
contracts/Synthetix.sol

Launched tests of `Synthetix.js` only:

Optimize totalIssuedSynths loop

---

publish/index.js
publish/src/commands/.gitignore
publish/src/commands/deploy.js
publish/src/commands/import-fee-periods.js
test/publish/index.js

This adds the import fee period script and a bunch of tests for the various scenarios.

Creating the import fee period script

---

contracts/RewardsDistribution.sol
publish/deployed/kovan/config.json
publish/deployed/kovan/synths.json

update config.json for release to kovan

update config.json for release to kovan

---

test/contracts/ExchangeState.js
test/contracts/Exchanger.js
test/contracts/Issuer.js
test/contracts/MultiCollateralSynth.js
test/contracts/Synth.js
test/utils/setupUtils.js

- Primarily added new ABI checker that only expected mutative functions exist from the contract
- Making sure all restricted mutative functions are indeed restrictive

SIP-37 Additional test coverage

---

contracts/ExchangeState.sol
contracts/Exchanger.sol
contracts/interfaces/IExchangeState.sol
test/contracts/ExchangeState.js

As ExchangeState will not be upgradable.

Persist the exchange fee rate in ExchangeState

---

contracts/AddressResolver.sol
contracts/EtherCollateral.sol
contracts/ExchangeRates.sol
contracts/ExchangeState.sol
contracts/Exchanger.sol
contracts/FeePool.sol
contracts/Issuer.sol
contracts/MixinResolver.sol
contracts/MultiCollateralSynth.sol
contracts/PurgeableSynth.sol
contracts/Synth.sol
contracts/Synthetix.sol
contracts/SynthetixState.sol
contracts/interfaces/IDepot.sol
contracts/interfaces/IExchangeState.sol
contracts/interfaces/IExchanger.sol
contracts/interfaces/ISynthetix.sol
contracts/test-helpers/MockEtherCollateral.sol

Note: the fix is in `Synthetix.sol` - I just also ran the formatter hence the spacing changes.

Fix Synthetix.isWaitingPeriod() and run format

---

.circleci/config.yml
contracts/MultiCollateralSynth.sol
package.json
test/contracts/MultiCollateralSynth.js
test/publish/index.js
test/testnet/index.js
test/utils/localUtils.js

Please don't merge yet - adding another spec to it.

Fixing testnet test

---

contracts/EtherCollateral.sol
test/contracts/EtherCollateral.js

Applied outstanding recommendations on SigP audit

Sip 35 rebased

---

contracts/EtherCollateral.sol
test/contracts/EtherCollateral.js

- [ x] removed view helper accountsWithOpenLoans
- [ x] added accountLoanLimit and setAccountLoanLimit
- [ x] Added these to getContractInfo for @evgenyboxer 
_issuanceRatio = issuanceRatio();
_interestPerSecond = interestPerSecond;

add loanLimit, remove accountsWithOpenLoans

---

publish/src/commands/deploy.js
test/publish/index.js

This tidies up the deploy script to better handle AddressResolver updates:
- If AddressResolver has not changed, then `importAddresses` is only called for any new contracts deployed (otherwise it will be called with all)
- If any contract with `setResolver()` does not have the current (or new) AddressResolver, invoke `setResolver()` with it. (Allowing for new AddressResolver deployments).

Improvements to deploy script for AddressResolver

---

README.md
contracts/FeePool.sol
contracts/SynthetixState.sol
migrations/2_deploy_synthetix_system.js
publish/deployed/local/synths.json
test/contracts/EtherCollateral.js
test/contracts/FeePool.js
test/contracts/RewardsIntegrationTests.js
test/publish/index.js

Remove xdr (reverted commit from release)

WIP - Remove xdr (reverted commit from release)

---

.solcover.js
migrations/2_deploy_synthetix_system.js
package.json
test/contracts/Depot.js
truffle.js

[Edited]
**PR targets #452**
It looks like technically [deployer.link is async][1] - not sure why it's being weird while running in the plugin but awaiting the links seems to make it work.
Other changes were necessary as well...leaving some notes in the diff.
Please feel free to close if this contains changes you're not interested in - just opened to make sure it's possible to get it working.
[1]: https://github.com/trufflesuite/truffle/blob/develop/packages/deployer/src/actions/link.js#L3-L7

Fix coverage migrations

---

.gitignore
.solcover.js
.travis.yml
migrations/2_deploy_synthetix_system.js
package-lock.json
package.json
test/contracts/Depot.js
truffle.js

Fixes coverage reports (thanks to @cgewecke) and adds codecov.io reports via travis

Upgrading solidity-coverage and using new plugin format

---

package-lock.json
package.json
test/publish/index.js

- Upgraded ganache-cli to `6.9.1`
- Upgraded web3 to `1.2.6`
- Added retry wrappers to all `.call()` invocations

Fix flaky publish tests

---

contracts/DelegateApprovals.sol

@clementbalestrat  change approvedAll to public func

change approvedAll to public func

---

README.md
bin.js
index.js
publish/src/commands/nominate.js
publish/src/commands/owner.js
publish/src/safe-utils.js
publish/src/util.js

- adding `getUsers` function to synthetix for system users
- adding `yes` flag to owner actions script
- adding default owner address parameter
- better error reporting when a non safe is connected
- adding default owner address parameter

Owner script and getUsers function

---

.circleci/config.yml
package.json
slither.config.json

Added slither support

---

publish/deployed/kovan/synths.json
publish/deployed/local/synths.json
publish/deployed/rinkeby/synths.json
publish/deployed/ropsten/synths.json

reset iETH limits

---

contracts/Synthetix.sol
contracts/interfaces/IDepot.sol
contracts/interfaces/IExchangeRates.sol
contracts/interfaces/IExchanger.sol
contracts/interfaces/IFeePool.sol
contracts/interfaces/IIssuer.sol
contracts/interfaces/ISynth.sol
contracts/interfaces/ISynthetix.sol

Adding the remainder of functionality that third parties may want to integrate with.

Interface improvements for third parties

---

publish/deployed/local/config.json
publish/src/commands/deploy.js
test/contracts/setup.js
test/testnet/index.js

- Changes to deploy script
- Changes to testing

Proxy migration phase 2

---

contracts/ExchangeRates.sol
contracts/FeePool.sol
contracts/RewardsDistribution.sol

- Removes all the extraneous checks I could find. 
- Added a comment about a require statement that seems to check uint >= 0 but is actually checking something else. 
- Moved a require statement as a minor optimization (I like to check memory data first before loading anything from storage).

Removed some extraneous checks

---

contracts/Proxy.sol
contracts/SynthetixState.sol
test/contracts/Depot.js
test/contracts/FeePoolEternalStorage.js
test/contracts/ProxyERC20.js
test/contracts/SynthetixState.js

Remove deprecated code
1. deprecate Proxy.setUseDELEGATECALL 
2. deprecate SynthetixState.setPreferredCurrency
Added tests for improved unit test coverage

Improve test Coverage 

---

contracts/Liquidations.sol
contracts/test-helpers/MockExchanger.sol
test/contracts/Issuer.js
test/contracts/Liquidations.js
test/contracts/Synthetix.js

- Changed flagAccForLiquidation to revert with msg if not within liquidation zone instead of passing
`require(accountsIssuanceRatio >= liquidationRatio, "Account issuance ratio is less than liquidation ratio");`

Sip 15 add more testcases

---

contracts/StakingRewards.sol
test/contracts/StakingRewards.js

Just a quicky for the the ERC Recover for external rewards

Add External Rewards Recovery function

---

publish/src/commands/deploy.js

Also ran on kovan to fix issue with Depot.

Deploy fix for old Depot pre SIP-46

---

buidler.config.js
publish/src/commands/build.js
publish/src/solidity.js

Replaces #554 
Also fixing buidler

Fix deploy size checks

---

.travis.yml
buidler.config.js
package-lock.json
test/contracts/BinaryOption.js
test/contracts/BinaryOptionMarket.js
test/contracts/BinaryOptionMarketManager.js

It works by skipping tests contained within a block with `@gas-skip` in the description. 
Here are all the mocha options for reference we could be using: https://mochajs.org/api/mocha

Fix gas reports

---

publish/deployed/kovan/synths.json

Rebalance based on:
https://docs.google.com/spreadsheets/d/1ucAM-9fyRdyKqyRLTUDLII5cNy7yYWKJ6Id0FrM3Oy4/edit#gid=0

rebalance sDEFI sCEX indices

---

contracts/StakingRewards.sol
publish/src/commands/release.js
test/contracts/StakingRewards.js

https://github.com/Synthetixio/SIPs/blob/master/SIPS/sip-68.md

Staking rewards pause stake

---

contracts/ExchangeRates.sol
contracts/MixinSystemSettings.sol
contracts/SystemSettings.sol
index.js
publish/src/commands/deploy.js
test/contracts/ExchangeRates.js
test/contracts/StakingRewards.js
test/contracts/SystemSettings.js
test/contracts/setup.js
test/publish/index.js

Adding `waitingPeriodSecs` into `SystemSettings`

Adding rateStalePeriod to SystemSettings

---

publish/src/commands/deploy.js

https://sips.synthetix.io/sccp/sccp-36
https://sips.synthetix.io/sccp/sccp-38
https://sips.synthetix.io/sccp/sccp-39

SCCP 36 38 39 temp increase fees for CL synths

---

contracts/ExternStateToken.sol
contracts/TokenState.sol
package.json
test/contracts/TokenState.js

Reverts Synthetixio/synthetix#595
base was set to master not develop.

Revert "Optimize SNX transfer/transferFrom gas upto 8k"

---

bin.js
publish/deployed/mainnet/rewards.json
test/deployments/index.js
test/etherscan/index.js
test/etherscan/spec.js

- Also adds `grep` option to etherscan tests

Fixing broken tests from staking reward checks

---

publish/deployed/kovan/synths.json
publish/deployed/rinkeby/synths.json
publish/deployed/ropsten/synths.json

```
{
"name": "iTRX",
"asset": "TRX",
"category": "crypto",
"sign": "",
"desc": "Inverse TRON",
"subclass": "PurgeableSynth",
"inverted": {
"entryPoint": 0.0299,
"upperLimit": 0.04485,
"lowerLimit": 0.01495
}
},
{
"name": "iXTZ",
"asset": "XTZ",
"category": "crypto",
"sign": "",
"desc": "Inverse Tezos",
"subclass": "PurgeableSynth",
"inverted": {
"entryPoint": 4.1915,
"upperLimit": 6.28725,
"lowerLimit": 2.09575
}
},
{
"name": "iXRP",
"asset": "XRP",
"category": "crypto",
"sign": "",
"desc": "Inverse Ripple",
"subclass": "PurgeableSynth",
"inverted": {
"entryPoint": 0.3042,
"upperLimit": 0.4563,
"lowerLimit": 0.1521
}
},
{
"name": "iLINK",
"asset": "LINK",
"category": "crypto",
"sign": "",
"desc": "Inverse Chainlink",
"subclass": "PurgeableSynth",
"inverted": {
"entryPoint": 19.54, …
```

reset isynths for testnets

---

publish/deployed/kovan/feeds.json
publish/deployed/kovan/synths.json
publish/deployed/mainnet/feeds.json
publish/deployed/mainnet/synths.json
publish/deployed/rinkeby/feeds.json
publish/deployed/rinkeby/synths.json
publish/deployed/ropsten/feeds.json
publish/deployed/ropsten/synths.json
test/deployments/index.js

Fixes all synths and feeds to match what's currently deployed in all environments

Adjusting synths and feeds.json to match currently deployed situation

---

package-lock.json
test/testnet/index.js

Minor fix in test/testnet/index.js, a bug that was introduced with the forking experiments. We should leave this file alone as we move forked tests to a dedicated test suite.
Also, not sure if package-lock.json is right. I pulled develop and performed a clean-install, which updated the file.

Bugfix on test:testnet

---

index.js
publish/deployed/kovan/versions.json

It failed during npm publish - see here https://app.circleci.com/pipelines/github/Synthetixio/releases/327/workflows/15091a09-80df-4384-9c6e-3caeeb4585b1/jobs/2407
So i fixed it and ran in manually via `node publish versions-update --version-tag 2.27.2-alpha --release Pollux`

Fixing versions finder

---

.circleci/config.yml

Addresses https://github.com/Synthetixio/synthetix-pm/issues/52.
Switch prod testing to Kovan to check if occasional failure in CI is persistent.

Switch network to Rinkeby for prod tests

---

package-lock.json
package.json
scripts/interactive-ui.js

This script goes through a deployment.json file (accepts `--network`, `--use-ovm`, etc) and presents Inquirer prompts to query any view function in any contract.
Eg.
```
➜ node scripts/interactive-ui.js
? Contract: Synthetix
? Function: name()
↪(string): Synthetix Network Token
```

Adds an interactive UI script

---

package-lock.json
scripts/airdrop.js
scripts/interactive-ui.js
scripts/utils/runTx.js
scripts/utils/setupProvider.js

Interactive script:
* can use forks
* can sign txs
Airdrop
* can use forks

Improves scripts

---

publish/deployed/goerli/deployment.json
publish/src/commands/owner.js
scripts/check-airdrop.js

* Updates Goerli L1 deployments with partial contract verification from etherscan
* Updates owner script to handle EOAs

Phase b progress

---

contracts/SecondaryDeposit.sol
package-lock.json
package.json
publish/deployed/goerli-ovm/params.json
publish/src/commands/deploy.js
scripts/utils/setupProvider.js

- Migrate SecondaryDeposit
-  Switch `isPrimary` flag to deactivate them
- Add events

Migrate SecondaryDeposit

---

scripts/ethdrop.js
scripts/interactive-ui.js

The script takes in a mnemonic and spins up N wallets to send ETH from. Ether is distributed between the sender wallets and an execution thread is started for each wallet, sending from +16 wallets at a time.

Adds a script for performing ETH airdrops

---

publish/deployed/kovan/feeds.json
publish/deployed/local/feeds.json
publish/deployed/mainnet/feeds.json
publish/deployed/rinkeby/feeds.json
publish/deployed/ropsten/feeds.json

AS per SCCP 53 , removing LEND from feeds.json 
https://gov.synthetix.io/#/synthetix/proposal/QmYh568EKEt5fETXtEE39dhpRcktTv65pjugra3LgCbJZk

remove LEND from feeds.json

---

package-lock.json
package.json
publish/src/util.js

- Also fixes issue in `PROVIDER_URL_MAINNET` from only being used for `network: mainnet`

Upgrading buidler-truffle5 to fix coverage issues

---

publish/deployed/mainnet/synths.json

Mirror of #844 with correct branch name

reset-ibtc-inverse-pricing

---

test/prod/Synthetix.prod.js

Same as #895, cherry picked to master

Skip vsynth prod test

---

package-lock.json
publish/src/commands/connect-bridge.js

Improves the connect-bridge script by having it read on-chain values before writing, and only writing diffs.

Improved connect-bridge script

---

contracts/Exchanger.sol
test/contracts/Exchanger.spec.js

Closed #934 to rename branch for merge into master

sip 98 double swing trade exchange fees

---

contracts/BaseRewardEscrowV2.sol
contracts/ImportableRewardEscrowV2.sol
contracts/RewardEscrowV2.sol
contracts/interfaces/IRewardEscrowV2.sol

@i-stam 
WIP - happy for this to be merged into sip-60-reward-escrow-v2 whenever:
- finalised migrateAccountEscrowBalances. 
- updated functions to check escrowMigrationPending / prevent users double-dipping on `migrateVestingSchedule`
- ratePerSecond calcs
- stub functions for vest() and _amountClaimable (To calculate the delta b/w lastVested and now to get amount that can be vested)

Reward escrow v2 migration contract

---

contracts/BaseRewardEscrowV2.sol
contracts/ImportableRewardEscrowV2.sol
contracts/RewardEscrowV2.sol
contracts/interfaces/IRewardEscrowV2.sol
test/contracts/BaseRewardEscrowV2.js

- TODO - Adding stub test cases in BaseRewardEscrowV2.js, RewardEscrowV2.js for 
- `vest()`
- `ratePerSecond()`
- `getVestingEntryClaimable()`
- `getVestingQuantity()`
- `timeSinceLastVested()`
- `appendVestingEntry()`
- `createEscrowEntry()`

Reward escrow V2 Vesting and calculating claimable amounts

---

package-lock.json
package.json
test/optimism/deposits.test.js
test/optimism/index.js
test/optimism/rewards.test.js
test/optimism/withdrawals.test.js

See https://www.npmjs.com/package/@eth-optimism/watcher

Adds watchers to L2 tests

---

contracts/BaseRewardEscrowV2.sol
contracts/RewardEscrowV2.sol
contracts/interfaces/IRewardEscrow.sol
test/contracts/Synthetix.js
test/contracts/setup.js

WIP -  pending change to whether we use `importVestingSchedule` to populate user's vesting entry data.

WIP -add importVestingSchedule for manual import of wallet's vesting entries

---

publish/src/commands/connect-bridge.js

There was a small bug I discovered when trying to run the script for connecting the bridges in Kovan and Kovan-ovm.
I made a quick fix and eliminated a bit of code, please take a look.

Fix connect-bridge.js bug

---

package-lock.json
package.json
test/optimism/index.js

Just a few changes and bugs I found while working on the kovan deployment branch, on order to keep the sip-60 updated.

Sip-60  Update

---

contracts/CollateralManager.sol
contracts/DebtCache.sol
contracts/interfaces/ICollateralManager.sol
index.js
publish/deployed/local/feeds.json
publish/src/commands/deploy.js
test/contracts/CollateralManager.js

-  debtCache to check if synthsByKey exists on collateralManager

update CollateralManager to addSynths + currencyKeys

---

index.js
publish/src/commands/deploy.js
test/contracts/CollateralEth.js

Pass the values in per second.

Staging interest parameter fix

---

contracts/CollateralManager.sol
publish/src/commands/deploy.js

Removes system status from collateral manager.

remove system status from collateral manager

---

publish/src/commands/deploy-ovm-pair.js

style: fix

---

test/contracts/SynthetixBridgeToOptimism.spec.js
test/contracts/setup.js
test/optimism/index.js
test/optimism/migrateEscrow.test.js
test/optimism/withdrawals.test.js

Extra escrow migration prod tests

---

contracts/SynthetixBridgeToBase.sol
contracts/SynthetixBridgeToOptimism.sol

This will also fix the broken tests from the changes in the `VestingEntry` struct.

Use abi.encodeWithSelector for encoding the L2 messages

---

index.js

Change max debt default to 30m

---

.circleci/config.yml
.circleci/src/jobs/job-prod-diff-tests.yml
.circleci/src/jobs/job-prod-tests.yml
.circleci/src/jobs/job-unit-tests-gas-report.yml
package.json

It didn't seem to help at all.

ci: revert fix for github auth issue on circleci

---

test/prod/BinaryOptions.prod.js

Added a prod test which runs the following BOM scenarios and prints reports for them:
- Create a market
- Bid
- Resolve

Adding a prod test for binary options

---

contracts/SynthetixBridgeToOptimism.sol
package-lock.json
test/contracts/SynthetixBridgeToOptimism.spec.js
test/contracts/SynthetixBridgeToOptimism.unit.js

Proposing this instead of #1230. Note however this is just for L1.

Adding forwarding functionality to optimistic bridge

---

publish/src/commands/connect-bridge.js

The connect bridge script checks if the signer is not the AddressResolver owner, and if so, prompts the user to sign that tx externally.

Minor improvement to connect bridge

---

contracts/EtherWrapper.sol
test/contracts/EtherWrapper.js

Context: https://kovan.etherscan.io/tx/0x38c4eeeab7a59ee0327ae9afddd05bfcae5d8aed9f5fc1353cc73bce6b753fd5

Fix for etherwrapper rounding/precision issue 

---

hardhat/util/describeSources.js

Without this, the docs cannot easily determine what is a view or not. https://github.com/Synthetixio/synthetix-docs/blob/master/scripts/build-contracts-ast-docs.js#L312

Ensuring ASTs have stateMutability

---

contracts/FuturesMarketManager.sol
contracts/test-helpers/MockFuturesMarket.sol
test/contracts/FuturesMarketManager.js

This adds a number of tests and implements a couple of fixes in the `FuturesMarketManager` contract.

Futures market management tests

---

contracts/BaseSynthetix.sol
contracts/Exchanger.sol
publish/releases.json
test/contracts/BaseSynthetix.js
test/contracts/Exchanger.spec.js

https://sips.synthetix.io/sips/sip-138

SIP-138 Update Volume Tracking Event

---

publish/src/commands/settle.js

Tested by enhancing the script to run properly on a fork of mainnet, and then doing the web3/ethers replacement.

Removed web3 from settle script

---

publish/src/commands/migrate-binary-option-markets.js

Remove web3 from migrate-binary-option-market script

Remove web3 from migrate-binary-option-markets

---

publish/src/Deployer.js
publish/src/command-utils/transact.js
publish/src/commands/deploy-shorting-rewards.js
publish/src/commands/deploy-staking-rewards.js
publish/src/commands/deploy/index.js
publish/src/commands/import-fee-periods.js
publish/src/commands/migrate-binary-option-markets.js
publish/src/commands/persist-tokens.js
publish/src/commands/purge-synths.js
publish/src/commands/remove-synths.js
publish/src/commands/replace-synths.js
publish/src/commands/settle.js
publish/src/commands/verify.js
publish/src/util.js
test/etherscan/spec.js

Support for Optimism's explorer links

Upgrading etherscan links to optimistic explorer when required

---

.eslintignore

Closes https://github.com/Synthetixio/synthetix-pm/issues/202

Add /optimism folder to .eslintignore

---

contracts/FuturesMarket.sol
contracts/FuturesMarketData.sol
contracts/FuturesMarketSettings.sol
contracts/interfaces/IFuturesMarket.sol
contracts/interfaces/IFuturesMarketSettings.sol

Addresses https://github.com/Synthetixio/issues/issues/100, and also moves the price invalidity check out of the `_canLiquidate` function, as this should have already been checked in all cases.

Futures Interface Cleanup

---

publish/index.js
publish/src/commands/accept-relay-owner.js

Add new script to bulk accept ownership by OwnerRelayOnOptimism. 
This script checks all contracts in L2 to see if OwnerRelayOnOptimism is nominated as new owner and in that case accepts ownership using the acceptOwnershipOn function.

Add acceptRelayOwner script

---

package-lock.json
package.json
test/contracts/CollateralErc20.js
test/contracts/CollateralEth.js

Release changes: https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.5.0

Update hardhat to 2.5.0

---

contracts/MixinResolver.sol

Cleanup MixinResolver removing unused imports.

MixingResolver remove unused imports

---

contracts/FuturesMarket.sol
contracts/FuturesMarketData.sol
contracts/interfaces/IFuturesMarket.sol
test/contracts/FuturesMarket.js
test/contracts/FuturesMarketData.js

Refs: https://github.com/Synthetixio/issues/issues/211

Futures order slippage

---

test/integration/dual/relayBatch.integration.js

Previous test was only testing batch relays by changing ownership to 2-3 contracts. This does all of them in a single call.

Updates batch relay tests to nominate ALL contracts

---

publish/src/commands/nominate-relay.js
publish/src/commands/nominate.js
publish/src/commands/owner-relay.js
publish/src/commands/owner.js

Some fixes done while doing the deploy and test of Governance-Relay on Kovan.
- Limit batch size for nominate-relay and owner-relay
- Remove unused parameters from the scripts
- Bug fixing while checking new-owner address
- Fix gasPrice/gasLimit for ovm (nominate.js)
- Wording

Fix Owner-relay and Nominate-relay

---

contracts/FuturesMarket.sol
test/contracts/FuturesMarket.js

* Emit the proper position id in position modified events.
* Delete position id upon position closure.

Fix futures position id management + tests.

---

.github/workflows/codeql-analysis.yml

check comparison

---

test/integration/behaviors/short.behavior.js

This causes fork and integration tests to fail now that [SCCP-146](https://sips.synthetix.io/sccp/sccp-146/) was implemented.

Skip shorts integration tests when cannot open loans

---

index.js
publish/src/commands/connect-bridge.js
publish/src/commands/nominate.js
publish/src/commands/owner.js

* Owner script fixes
* Adding L2 relayer as owner

Fixes from menkalinan

---

publish/deployed/mainnet/deployment.json
test/contracts/CollateralShort.js

Fixing
```
Contract: CollateralShort
"before all" hook for "should ensure only expected functions are mutative":
Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; i
```

Fix broken unit test

---

contracts/FuturesMarket.sol
contracts/FuturesMarketBase.sol
contracts/MixinFuturesViews.sol
contracts/interfaces/IFuturesMarketBaseTypes.sol
test/contracts/FuturesMarket.js
test/contracts/FuturesMarketData.js

Minor refactor to reduce clutter in main futures contract.

refactor views into mixin to reduce clutter

---

contracts/ExchangeCircuitBreaker.sol
contracts/ExchangeRates.sol
contracts/Exchanger.sol
contracts/FuturesMarket.sol
contracts/FuturesMarketBase.sol
contracts/MixinFuturesNextPriceOrders.sol
contracts/interfaces/IExchangeCircuitBreaker.sol
publish/deployed/local-ovm/config.json
publish/deployed/local/config.json
publish/src/commands/deploy/configure-legacy-settings.js
publish/src/commands/deploy/deploy-core.js
test/contracts/ExchangeCircuitBreaker.js
test/contracts/ExchangerWithVirtualSynth.behaviors.js
test/contracts/FuturesMarket.js
test/contracts/FuturesMarket.nextPrice.js
test/contracts/FuturesMarketData.js
test/contracts/setup.js

rename circuit breaker contracts

---

contracts/MixinSystemSettings.sol
contracts/SystemSettings.sol
contracts/SystemSettingsLib.sol
hardhat.config.js
test/contracts/SystemSettings.js
test/integration/behaviors/stake.behavior.js
test/integration/utils/rates.js

Addressing comments and small fixes for https://github.com/Synthetixio/synthetix/pull/1627/files

SIP 193 handover changes

---

publish/deployed/mainnet-ovm/config.json
publish/deployed/mainnet-ovm/deployment.json
publish/deployed/mainnet-ovm/rewards.json
publish/src/commands/deploy-staking-rewards.js

Patch release `v2.57.2` to include `Deploy SNX/ETH and sUSD/DAI staking rewards on OVM (#1653)` from https://github.com/Synthetixio/synthetix/commit/b3012b0c799030bbceb44e4a0a22c15312e81baf

Patch release v2.57.2 to mainnet ovm

---

publish/assets.json
publish/deployed/kovan-ovm/config.json
publish/deployed/kovan-ovm/deployment.json
publish/deployed/kovan-ovm/feeds.json
publish/deployed/kovan-ovm/params.json
publish/deployed/kovan-ovm/synths.json
publish/src/commands/deploy-migration.js

`sAVAX`: [0xBc9F23b1AEf25e9a456F1973E9a9ef63830B8f49](https://kovan-optimistic.etherscan.io/address/0xBc9F23b1AEf25e9a456F1973E9a9ef63830B8f49)
`sMATIC`: [0x5BC3b2B2dC40dC88ea227F7501F28D9D8167BB60](https://kovan-optimistic.etherscan.io/address/0x5BC3b2B2dC40dC88ea227F7501F28D9D8167BB60)

Add synths sAVAX and sMATIC to kovan ovm

---

publish/assets.json
publish/deployed/mainnet-ovm/config.json
publish/deployed/mainnet-ovm/deployment.json
publish/deployed/mainnet-ovm/feeds.json
publish/deployed/mainnet-ovm/params.json
publish/deployed/mainnet-ovm/synths.json
publish/releases.json
publish/src/commands/deploy-migration.js

Runsheet: https://www.notion.so/Algieba-v2-63-19f7c16f46a14e8484cef34ac394c13f
SIPs: https://sips.synthetix.io/sips/sip-205/

Algieba release v2.63 to mainnet ovm

---

contracts/ExchangeRatesWithDexPricing.sol
contracts/ExchangerWithFeeRecAlternatives.sol
contracts/MixinSystemSettings.sol
contracts/SystemSettings.sol

Implementation of the suggestion here, for discussion: https://github.com/Synthetixio/synthetix/pull/1667#discussion_r802255506

SIP-198: Atomic Configuration Getter Method

---

test/integration/behaviors/short.behavior.js

Short integration tests were failing to open since the Synth wasn't added as shortable in the test setup

Fix short integration test on non-fork

---

package-lock.json
package.json

upgrading to the new version with usability improvements

upgrade hardhat interact

---

publish/src/commands/build.js
publish/src/commands/deploy/add-synths-to-protocol.js
test/integration/utils/deploy.js

deploy script changes for external use (internal)

---

index.js

SIP-231: Offchain Circuit Breaker

---

publish/src/commands/deploy/rebuild-legacy-resolver-caches.js

https://github.com/Synthetixio/project-management/issues/183

Rebuild caches for legacy contracts on L2

---

contracts/RewardEscrowV2StorageMixin.sol

branching off https://github.com/Synthetixio/synthetix/pull/1816 to check CI

Escrow liquidation

---

.circleci/config.yml
.circleci/src/snippets/job-header-machine.yml
.gitignore

ci: use ubuntu@lts (22)

---

contracts/BaseRewardEscrowV2.sol
contracts/BaseSynthetix.sol
contracts/ImportableRewardEscrowV2.sol
contracts/Issuer.sol
contracts/Liquidator.sol
contracts/MintableSynthetix.sol
contracts/RewardEscrowV2.sol
contracts/RewardEscrowV2Storage.sol
contracts/Synthetix.sol
contracts/interfaces/IRewardEscrowV2.sol
contracts/interfaces/ISynthetix.sol
publish/src/commands/deploy/configure-legacy-settings.js
publish/src/commands/deploy/configure-reward-escrow.js
test/contracts/BaseRewardEscrowV2.js
test/contracts/Liquidator.js
test/contracts/RewardEscrowV2Storage.js
test/contracts/setup.js

Collecting changes added after internal review start (in order to stop changing reviewed PR) for https://github.com/Synthetixio/synthetix/pull/1825

[draft]: internal review changes to #1825

---

publish/src/commands/deploy/configure-futures.js

Minor fix to futures configuration script so that it will use correct default values instead of settling for just anything that's not zero.

update futures settings to correct values

---

publish/deployed/goerli-ovm/index.js
publish/deployed/goerli/index.js

- Index.js file for other network always export futures-markets.json

Goerli-ovm have futures market deployed

---

contracts/ExchangeCircuitBreaker.sol
contracts/PerpsEngineV2Base.sol
contracts/interfaces/IFuturesMarketBaseTypes.sol
contracts/interfaces/IPerpsInterfacesV2.sol

Fix some typos on comments (spoted while reading code)

Fix comment typos

---

.github/workflows/slither-analysis.yml

ci: use dockerhub for slither

---

package-lock.json
package.json

fix: npm audit critical vulnerability (override loader-utils)

---

test/integration/behaviors/liquidations.behavior.js

fixed an issue by ensuring mocked rates were being set properly

fix: integration test failure

---

publish/deployed/goerli-ovm/perpsv2-markets.json
publish/deployed/local-ovm/perpsv2-markets.json
publish/src/commands/deploy/configure-perpsv2.js

This PR introduces the following changes:
- Add pause flag to off-chain virtual market,
- Add flag to perpsv2-market.json files
- Fix off-chain delayer order min and max age number format

PerpsV2: Deployment script fixes

---

publish/releases.json
publish/src/Deployer.js
publish/src/commands/deploy/deploy-perpsv2.js

Perpsv2 deployer improvements

---

README.md

Duplicate https://github.com/Synthetixio/synthetix/pull/1895

Fix: Discord link + typos

---

.circleci/config.yml
.circleci/src/snippets/job-header-machine.yml
package-lock.json
package.json
test/integration/behaviors/futures.behavior.js
test/integration/behaviors/perpsV2.behavior.js

- fix audit ✅ 
- fix fork-test ovm ✅ 
- fix publish test timeout  ✅

Fix CI test failing

---

publish/deployed/goerli-ovm/feeds.json
publish/deployed/goerli-ovm/perpsv2-markets.json
publish/deployed/mainnet-ovm/perpsv2-markets.json

Executes [SCCP-2036](https://sips.synthetix.io/sccp/sccp-2036) and updates the fake feeds on optimism goerli as per the chainlink [addresses](https://docs.chain.link/data-feeds/price-feeds)

Update Optimism Goerli Chainlink Feeds  / Executes SCCP-2036

---

contracts/PerpsV2MarketViews.sol

picked up by guardian while auditing leverage token. 
slight inaccuracy in the comments due to some nesting of brackets.
rest of changes is just autoformatter.

fix comment inaccuracy in liquidation view function
