Synthetixio/synthetix

contracts/Court.sol
deploy.py

Allow the deploy script to print the addresses of the contracts it deploys, and the addresses pointing to the owner, oracle, and initial liquidation beneficiary.
Additionally tags a non-state-modifying function as a view, without changing any of its logic.

Print deploy addresses

---

contracts/ERC20FeeToken.sol
contracts/ERC20Token.sol

* ERC20Token.transfer, ERC20FeeToken.transfer require a nonzero recipient.
* ERC20Token.transferFrom, ERC20FeeToken.transferFrom require nonzero sender and recipient.
* ERC20FeeToken.withdrawFee does nothing if zero fees are withdrawn.

Disallow transfers to and from the zero address in ERC20 functions.

---

contracts/Court.sol
contracts/EtherNomin.sol
tests/contracts/FakeCourt.sol
tests/contracts/PublicCourt.sol
tests/test_Court.py
tests/test_EtherNomin.py

- Allow users to vote on multiple votes at once.
- Refactoring and renaming of various bits and pieces in Court.sol.
- People can't vote on motions involving themselves.

Multi vote

---

contracts/ExternStateToken.sol
contracts/FeeToken.sol
contracts/Havven.sol
contracts/Nomin.sol
tests/contract_interfaces/fee_token_interface.py
tests/contract_interfaces/havven_interface.py
tests/contracts/PublicEST.sol
tests/contracts/PublicFeeToken.sol
tests/contracts/PublicHavven.sol
tests/contracts/PublicNomin.sol
tests/test_Court.py
tests/test_ExternStateToken.py
tests/test_FeeCollection.py
tests/test_FeeToken.py
tests/test_Havven.py
tests/test_HavvenEscrow.py
tests/test_Issuance.py
tests/test_IssuanceController.py
tests/test_Nomin.py
tests/test_Proxy.py
utils/deployutils.py

- added two arrays to constructor, to set issuers/nominsIssued for current issuers
- within transfers changed checking availableHavvens(sender) to new function transferableHavvens(sender)
- changed withdrawFee() to be external, from public
- changed name updateIssuanceData to computeIssuanceData
- changed remainingIssuableNomins to use safeSub
- added collateral function: havven.balanceOf(addr) + escrow.balanceOf(addr)
- renamed lockedHavvens to issuanceDraft, as it can go over the collateral of an address
- added lockedHavvens function, which caps the issuanceDraft up to the collateral of an address
- added transferableHavvens function which returns the number of havvens a user can transfer, considering the amount they have locked
- changed availableHavvens to use the collateral function …

small changes to havven to add basic functions and cleanup

---

contracts/FeePool.sol

If users tried to claim fees and there were no XDR synths in the system, it would divide by zero. Now it just tells the user that they have no fees available to claim.

Protecting against a divide by zero problem

---

contracts/ExchangeRates.sol
migrations/2_deploy_synthetix_system.js
test/ExchangeRates.js
test/FeePool.js
test/Synth.js
test/Synthetix.js

A bunch of assumptions in the code break if we're able to set `sUSD` rate to anything other than UNIT. This PR enforces that sUSD is not able to be set by the oracle, and updates the tests / deployment script accordingly.
I also renamed `Nomin.js` to `Synth.js` in the test files.

Now insisting on stable sUSD rate

---

.gitattributes
publish/index.js

This should remove tests from showing up as language detection, and highlight Solidity as the majority language not JavaScript.

Removing tests from language detection

---

contracts/ExchangeRates.sol
contracts/Synthetix.sol

Hi,
**Each separate commit could be considered as separate optimization:**
- (1e2196d59bbd921bce144195e00d198548c64c28) Rates storage optimization
- (8dee408f558a60ad8980f536fa3b65a36be02a68) Join multiple rates calls into single
- (e5a2fe2a102b66e9c09bfd604a2bffd437d0259a) Remove duplicate stale rate check
- (247339d8edb9536b2e8da7ec501333b2489dd491) Added reverse cache for synth currencyKeys
//
I believe `uint40` should be enough for storing seconds (up to 35 000 years).
It seems like 27.77% gas optimization for **avg** `ExchangeRates.updateRates`.
`alpha` (2eaef0dddf95d6c0e3a1acd4a96482aab8143d30):
```
·--------------------------------------------------------|---------------------------|-------------|----------------------------·
|          Solc version: 0.4.25+commit.59dbf8f1 …
```

Optimize rates storage

---

.solhint.json
.vscode/settings.json
contracts/Depot.sol
contracts/Synthetix.sol
contracts/interfaces/IERC20.sol
contracts/interfaces/ISynth.sol
package-lock.json
package.json
publish/src/commands/deploy.js
test/Synthetix.js
truffle.js

A few fixes here
1. Cleaned up solhint rules
2. Better VSCode and solhint integration
3. Minor fix to `Synthetix.exchange` to reduce gas (from `6,770,253` to `6,742,558`) 
4. Minor upgrade of `truffle` and `web3`
5. Fixed `solhint` to take quoted glob (so that it actually checks subdirectories correctly)
6. Cleaned up test coverage of SIP-21
7. Fixed deploy script

Rigil fixes for alpha, solhint cleanup and Synthetix swing trade reduction

---

contracts/Synthetix.sol
test/Synthetix.js

This adds the following `view` to `Synthetix`: `feeRateForExchange(bytes32 source, bytes32 dest)`. This allows dApps and, more importantly, other contracts to determine what the fee would be a given `exchange`.
It adds gas to the `Synthetix` contract deployment, but only around `4k`: from `6,742,579` to `6,746,386` (as you can [see here in gas checks](https://github.com/Synthetixio/synthetix/runs/293117793))

Adding in view to read fee rate for exchange

---

contracts/ExchangeRates.sol
publish/src/commands/deploy.js
test/publish/index.js

If the synths.json has an `aggregator` field, include it in the deployment configuration. (This is particularly important in future upgrades to `ExchangeRates`).

Add aggregators to deployment script via synths.json

---

contracts/ExchangeRates.sol
docs/content/contracts/ExchangeRates.md
test/contracts/ExchangeRates.js
test/publish/index.js

In order to migrate to Chainlink aggregators, our XDR rate can no longer be calculated on-chain when an XDR participating rate is updated, as these events happen in external Aggregators, which we have no control over. Instead, the XDR rate must be determined at request time.

XDR rate to no longer be calculated as a rate update

---

publish/deployed/kovan/synths.json
publish/src/Deployer.js
publish/src/commands/deploy.js
publish/src/util.js

This fixes a few issues with the deployment script:
1. When not deploying a new `ExchangeRates`, this will no longer try to run `setInversePricing` unless the inverse parameters have changed;
2. `FeePool.targetThreshold` is checked to be `1%` as per https://sips.synthetix.io/sccp/sccp-6
3. Adds the useful `dryRun` feature to deploys

Deployment script fixes

---

publish/deployed/local/config.json
publish/deployed/local/synths.json
publish/src/commands/deploy.js

- Important that EtherCollateral is set on Synthetix
- Synthetix relies on EtherCollateral.totalIssuedSynth() to exclude supply from issuedSynths / debt attributable to minters and ether collateral.

add ethercollateral and MultiCollateralSynth to deployment script

---

contracts/EtherCollateral.sol
contracts/ExchangeRates.sol
contracts/Exchanger.sol
contracts/FeePool.sol
contracts/Issuer.sol
contracts/MultiCollateralSynth.sol
contracts/PurgeableSynth.sol
contracts/Synth.sol
contracts/Synthetix.sol
test/contracts/ExchangeRates.js

1. Gas improvements in all `addressResolver` getters
2. Removing `ExchangeRates.rates()` (it was redundant - converted to internal `getRate()` and `rateForCurrency()` was changed to `external`.
3. Variable renames in `ExchangeRates`
4. Spelling issues in a couple of contracts.

Resolver reclaimer audit remediations

---

contracts/Exchanger.sol
contracts/Synthetix.sol
contracts/SynthetixState.sol
contracts/interfaces/ISynthetix.sol
test/contracts/Exchanger.js
test/contracts/FeePool.js
test/contracts/PurgeableSynth.js
test/contracts/RewardsIntegrationTests.js

cc @clementbalestrat @evgenyboxer - please make sure the dApps no longer reference `Synthetix.effectiveValue()` but rather invoke the same function on `ExchangeRates`

Remove Synthetix.effectiveValue in favor of ExchangeRates.effectiveValue

---

contracts/Synth.sol
test/contracts/Synth.js

- synth.transfer() to 0x address will be burned internally
- ExternStateToken is unmodified as Synthetix inherits and doesn't have erc20 burn implemented.

synth transfers to 0x address will be burned internally

---

contracts/Exchanger.sol
contracts/Issuer.sol
contracts/Synth.sol
contracts/Synthetix.sol
contracts/interfaces/IExchanger.sol
contracts/interfaces/ISynthetix.sol
contracts/test-helpers/MockExchanger.sol
test/contracts/Exchanger.js
test/contracts/Issuer.js
test/contracts/Synth.js

This fix prevents the known side-effect of SIP-37 whereby exchanges with invalid amounts are succeeding with 0 amounts. Instead they should `revert` unless a settlement was required, in which case they should continue to pass (and thereby emptying out the settlement queue).
E.g. https://etherscan.io/tx/0x9a92ca42aa216b1cb406e1b09c50062b90ec2bfb5f10e584cc19978c5eece4a4 
For Exchanger.exchange, Issuer.burnSynths, Synth.transferAndSettle, Synth.transferFromAndSettle we will only reduce the amount down to the user's balance if there was any settlement. This means invalid amounts, instead of quietly succeeding as 0, will revert as they used to

SIP-47 Ensure only exchanges with settlements adjust amounts down

---

contracts/DelegateApprovals.sol
contracts/interfaces/IDelegateApprovals.sol
test/contracts/DelegateApprovals.js

Sip10 delegate approvals audit remediations

---

.circleci/config.yml
package.json
test/deployments/index.js
test/etherscan/index.js
test/etherscan/spec.js

This will stop spurious failures from checking Etherscan ABIs each commit, and only run them on merging into named release branches - `master`, `release-candidate`, `beta` and `alpha`

Splitting deployments test into an etherscan ABI check

---

contracts/Issuer.sol
test/contracts/Issuer.js

set default min stake time
- can be updated to go into develop after migrating-to-buiilder is merged into develop

set default min stake time

---

.circleci/config.yml
buidler.config.js
publish/src/commands/build.js
publish/src/commands/verify.js
publish/src/contract-size.js
publish/src/solidity.js

Ensure the buidler tests uses optimized sources when requested, and output compiled sizes.
Run via `npx buidler compile --showsize --optimizer`
Added both opts to circleci, so it will fail if the contract is oversize (as using `--optimizer` will disable `allowUnlimitedContractSize`)
* `--showsize` output file sizes
* `--optimizer` enable the optimizer to run with `200` runs

Adding contract size output to compile task for buidler

---

contracts/Issuer.sol
contracts/PurgeableSynth.sol
contracts/Synthetix.sol
contracts/interfaces/IIssuer.sol
contracts/interfaces/ISynthetix.sol
test/contracts/Depot.js
test/contracts/Exchanger.js
test/contracts/Issuer.js
test/contracts/MultiCollateralSynth.js
test/contracts/RewardsDistribution.js
test/contracts/Synthetix.js
test/contracts/setup.js

Here is a proposal for how to reduce size of Synthetix, by moving issuance-specific views over and keeping.
This is a PR into the SIP-48 branch of #451.
These are the contract size of `develop` (not rates stale)
And these are the contract size of this:
I'm going to add average gas prices for issuance actions here shortly to compare

Moving issuance views to issuer (for SIP-48)

---

buidler.config.js
contracts/Proxy.sol
legacy/buidler.legacy.js
test/contracts/Exchanger.js
test/contracts/FeePool.js
test/contracts/Issuer.js
test/contracts/Synth.js
test/contracts/Synthetix.js

Provides a new flag `--gasprofile` to `buidler test` that only runs a handful of tests and outputs their gas usage. (Once #503 is merged, this can simply use that to show gas and this just becomes a small filter of tests to run to profile gas)

Adding --gasprofile to tests

---

publish/deployed/kovan/deployment.json
test/deployments/index.js
test/publish/index.js

This PR makes sure all testnet labels match mainnet from Phase 2 (https://docs.synthetix.io/integrations/guide/#proxies)
- `ProxyERC20` on all environments is a `ProxyERC20.sol` and `target` is `Synthetix`
- All `Synthetix` contracts have `proxy` set to `ProxyERC20` and `integrationProxy` set to the old `ProxySynthetix`
- `ProxyERC20sUSD` on all environments is a `ProxyERC20.sol` and `target` is `SynthsUSD`
- All `SynthsUSD` contracts have `proxy` set to `ProxyERC20sUSD` and `integrationProxy` set to the old `ProxysUSD`

Fixing proxy labelling and connections on testnets

---

contracts/Exchanger.sol
contracts/Issuer.sol
contracts/PurgeableSynth.sol
contracts/Synthetix.sol
test/contracts/Exchanger.js
test/contracts/Issuer.js
test/contracts/PurgeableSynth.js

- `Exchanger.remitFee` - removed redundant functions
- Added missing test coverage for `totalIssuedSynths` in `SNX` and in `ETH`
- Removed old comments from `Issuer` and `Exchanger`
- Staleness check on `src` and `dest` of `exchange()`
- Moved stale check of `src` and `dest` from `Synthetix` to `Exchanger` so `Synth._transferToFeeAddress` checks staleness no
- Removed specific check in `PurgeableSynth.purge` as staleness is now checked in `Exchanger`

SIP-48 audit remediations

---

publish/index.js
publish/src/commands/.gitignore
publish/src/commands/import-fee-periods.js
publish/src/commands/settle.js
test/publish/index.js
test/testnet/index.js

This command helps clear out all unsettled exchanges from `ExchangeState` in some network.
This is necessary before either a replacement of `ExchangeRates` or an upgrade of any aggregator in `ExchangeRates`. This is because SIP-37 tracks `roundId` parameters for a synth, and this would be lost in any upgrade.
Additionally, this command can be invoked to clear our all `ExchangeState` entries, allowing it to be replaced. 
Run:
```bash
$ node publish settle --network kovan --gas-price 3 --latest --old-proxy
```
> Old proxy is for unsettled exchanges emitted on the old `ProxySynthetix` in any network. These were migrated to Phase 2 on May 11, so once these have all been settled on all environments, this support should be removed from here.
> **Note**: due to SIP-44, if a synth is suspended it …

New settlement command

---

contracts/ContractStorage.sol
contracts/FlexibleStorage.sol
contracts/test-helpers/MockContractStorage.sol
test/contracts/ContractStorage.js
test/contracts/FlexibleStorage.js

This basically removes some of the useful logic from `FlexibleStorage` and puts it into it's own abstract class for potential reuse. You can think of `ContractStorage` as like a `State` contract that knows about the `AddressResolver`.

Migrating base logic to ContractStorage for reuse

---

contracts/ExternStateToken.sol
contracts/TokenState.sol
package.json
test/contracts/TokenState.js

Introducing and calling one `transferBalance()` instead of 2 `balanceOf()` and 2 `setBalanceOf()` would reduce CALL and SLOAD intructions which have prices of 700 and 800 gas respectively.
```
·------------------------------------------------------|---------------------------|-------------|-------------------------------------·
|                 Solc version: 0.5.16                 ·  Optimizer enabled: true  ·  Runs: 200  ·  Block limit: 9007199254740991 gas  │
·······················································|···························|·············|······································
|  Methods                                             ·               32 gwei/gas               ·           239.90 usd/eth            │ …
```

Optimize SNX transfer/transferFrom gas upto 8k

---

bin.js
index.js
package-lock.json
package.json

Creates a new decode functionality for transactions that target the Synthetix ecosystem.
> Note: I've opted for `util.inspect` instead of `JSON.stringify` as the former can output ANSI colo(u)?rs. I suspect that's better in 99% of cases so I propose to make it a default

Addind decode functionality to binary

---

index.js

Adding these to defaults as this is necessary because SIP-64 introduces a new `SystemSettings` contract where these will first be set.

Adjusting defaults to SCCP-43

---

contracts/Owned.sol
contracts/Proxyable.sol

Some of the contracts are starting to have bytecode size above the limit of what can be deployed in mainnet (24kb) (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md).
This PR performs a surgical change to reduce the contract size of Synthetix.sol (changes as little code as possible). The reduction is achieved by using internal functions in base modifiers, which avoids inlining in such modifiers. Operation gas costs should increase marginally, and deployment gas costs greatly.
Contract | Size | Size change
-------- | ---- | -----------
AddressListLib.sol | 82 Bytes (0.33%)
AddressResolver.sol | 2.41 KB (10.04%) | -3.75%
BinaryOption.sol | 5.2 KB (21.66%)
BinaryOptionMarket.sol | 15.64 KB (65.17%) | -2.53%
BinaryOptionMarketData.sol | 5.2 KB (21.68%) …

Avoid inlining in some modifiers

---

buidler.config.js
codechecks.yml

#722 
Synthetix is using a beta version of the gas-reporter that's buidlerevm-compatible when the `fast` option is enabled. It wraps the provider in a way which doesn't work for ganache. Disabling `fast` asks the reporter to fall back on it's default logic (e.g slow) ...
Also saw the diff is missing from the codechecks report since the migration to CircleCI in #684. Codechecks has [trouble discovering the commit hash][1] of the merge target in CircleCI unless it knows the branch name - have added some config to the `.yml` to help with this. Hopefully it will start to record the run history again and make target comparison possible.
[1]: https://github.com/codechecks/docs/blob/master/configuration.md#settings

Fix buildler-gas-reporter production reports

---

buidler.config.js
codechecks.yml

The same as #723. We are just using an internal branch to be able to bypass the errors returned by CI when using a branch from a forked repo.

Fix buildler-gas-reporter production reports (internal PR)

---

index.js
publish/assets.json
test/publish/index.js

There are some inconsistencies in the assets / tokens / synths with regards to `desc` and `description`. This aligns everything to use `description`.

Using consistent description for tokens, synths and assets

---

publish/deployed/local-ovm/config.json
publish/src/commands/deploy.js
test/multi/index.js
test/publish/index.js
test/testnet/index.js

Removes redundant `network === 'local'` checks in the deploy script. The `freshDeploy` flag should be enough.

Use freshDeploy in deploy script

---

.gitignore
scripts/airdrop.js
scripts/utils/runTx.js
scripts/utils/setupProvider.js

The main difference with the previous script is that this one doesn't check on-chain balances since these could change while the script is running. Instead, this produces a local file to keep track of what has already been transferred.

Proposes a new way to perform L2 airdrops

---

scripts/airdrop.js

Fixes a minor bug I found while testing `staker.collateral` => `staker.transferred`

Rename output field

---

.circleci/config.yml

Previously, prod tests for all networks were run only when merging to develop. With this change, this remains true, except mainnet prod tests are done on *every* PR.

Always perform prod tests for mainnet

---

.solcover.js
package-lock.json
package.json

Per [#732 comment][1]: compilation has been failing after instrumenting contracts for coverage. The error looks like:
```
Compiling...
Downloading compiler version 0.5.16
* Line 1, Column 1
Syntax error: value, object or array expected.
* Line 1, Column 2
Extra non-whitespace after JSON value.
> solidity-coverage cleaning up, shutting down ganache server
```
Believe this is solcjs crashing on the size of the JSON object passed to it for compilation. Instrumentation is adding a lot of Solidity code to the files and you have > 120 contracts, some of which are large. 
PR updates solidity-coverage to use some new options that reduce the instrumentation footprint by 
40 - 50%. It disables data collection for Istanbul's statement and function measures, (neither of which are tracked by codecov) …

Upgrade solidity-coverage to 0.7.11

---

scripts/airdrop.js
scripts/interactive-ui.js
scripts/utils/runTx.js

Ethers transaction lifecycle is:
1. TransactionRequest => A simple object describing a transaction
2. TransactionResponse => A receipt from the VM once it has been submitted to the network.
3. TransactionReceipt => A receipt for after the transaction has been mined.
The `runTx` script utility is designed to catch errors so that errors can be printed out in the console without breaking program execution. Before this PR, it was only catching errors between steps 2 & 3, and not between 1 & 2.

Fix interactive ui errors

---

.circleci/config.yml
.circleci/src/commands/fork_test_prod.yml
.circleci/src/jobs/gas-report.yml
.circleci/src/workflows/forkprod-tests.yml
buidler.config.js
codechecks.prod.yml
codechecks.unit.yml
package-lock.json
package.json

I requested this feature in eth-gas-reporter: https://github.com/cgewecke/eth-gas-reporter/issues/217
This produces a new gas report in the "Checks" section and causes CI to fail if a method call consumes more than 25% than it did before.
Note that the "prod gas report" will only be produced on commits to the develop branch.

Implements two gas reports, one for unit tests, and another for prod tests

---

.env.example
publish/src/commands/deploy.js
publish/src/commands/fork.js
publish/src/util.js

Adds a new PROVIDER_URL_MAINNET to .env. Scripts like deploy, fork, etc will use this provider instead of PROVIDER_URL if available.
Should be handy for using a specialized provider for mainnet in CI production tests.

Use preferred mainnet provider if available

---

.solhint.json

Adds a rule to .solhint.json, to allow 17 state declaration counts and remove the warning being emitted in contracts/EtherCollateralsUSD.sol

Remove solhint warning

---

.circleci/config.yml
.circleci/src/commands/cmd-local-start.yml
.circleci/src/jobs/job-production-tests-differential.yml
.circleci/src/jobs/job-production-tests-local-ovm.yml
.circleci/src/jobs/job-production-tests-local.yml
.circleci/src/workflows/workflow-scheduled.yml
.circleci/src/workflows/workflow-staging.yml
buidler.config.js
index.js
publish/deployed/local-ovm/config.json
publish/src/commands/deploy.js
test/prod/EtherCollateral.prod.js
test/prod/ExchangeRates.prod.js
test/prod/Synthetix.prod.js
test/prod/TradingRewards.prod.js
test/prod/utils/bootstrapLocal.js
test/prod/utils/connectContract.js
test/prod/utils/exchangeSynths.js
test/prod/utils/getTokens.js
test/prod/utils/index.js
test/prod/utils/skipWaiting.js
test/prod/utils/systemSettings.js

Allows starting a local chain with
`npx buidler node`
And running production tests against it:
`npm run test:prod`
The exact details of how to run the tests in each case can be found in the 2 new ci jobs that come in the PR:
`job-production-tests-local` and `job-production-tests-local-ovm`
The OVM tests compile regular EVM artifacts, but deploy an OVM configuration in the local chain. Note that this does not test the OVM bridge, simply that the deployed instance can perform basic production functionalities like transfer, exchange, etc.

Enables production tests on local environments

---

package.json

After @justinjmoses' comment in a previous attempt to speed up linting in the pre-commit hook, I understood how `pretty-quick` works.
We don't need to run `npm run lint` in the hook. Running `pretty-quick --staged --verbose` (notice the extra `--verbose` is more than enough) and is incredibly fast.

Improved linting in pre-commit hook

---

test/prod/Synthetix.prod.js

We're studying the ganache-core bug with the Truffle team, but on the meantime, we could disable this particular test so CI passes again.

Workaround to fix vSynth prod tests "settled" error

---

publish/src/commands/build.js

This is particularly important when compiling contracts for an ovm deploy. Some contracts may be ignored in `ovm-ignore.json` but included in a target ovm deployment like `publish/deployed/goerli-ovm`, which may result in evm code being deployed in the ovm.

Adds a --clean-build flag to the build command

---

package.json

A recent PR attempted to speed up our lint pre-commit hook: https://github.com/Synthetixio/synthetix/pull/890
Unfortunately, it assumed that `pretty-quick` performed eslint linting, but it does not. Reverting that change here.
An older approach is still viable: https://github.com/Synthetixio/synthetix/pull/884

Fix lint pre-commit hook

---

.circleci/config.yml
.circleci/src/workflows/workflow-master.yml

`job-validate-etherscan`, used in `workflow-master` is having the problem that it can't handle different instances of the same contract with different ABIs. Thus, until it's fixed, it needs to be disabled for CI checks to pass.
For example, some synth proxies may be updated and some not, resulting in the former to have interface A, and the latter having interface A'. Since our deployment files only store the latest interface, the etherscan check has no way of knowing which is which.

Disable etherscan checks in CI

---

.prettierignore
.pretty-quick-ignore

When pretty-quick was moved from a bash script to package.json, I forgot to add `--ignore-path .pretty-quick-ignore`, which was causing pretty-quick to fail in the lint hook, on any circleci file change.
This fixes that, but also in a simpler way, dropping `.pretty-quick-ignore` in favor of `.prettierignore` and adding all yaml/mustache templates there.

Add circleci paths to prettierignore for pretty-quick

---

.circleci/config.yml
.circleci/src/jobs/job-test-deploy-script.yml
.circleci/src/jobs/job-unit-tests-coverage.yml
.circleci/src/jobs/job-unit-tests-legacy.yml
.circleci/src/jobs/job-unit-tests.yml
.circleci/src/workflows/workflow-scheduled.yml
.circleci/src/workflows/workflow-staging.yml

Atm, hardhat forking only works for mainnet. Additionally, we want to reduce the CI load, so forking tests will only be done on mainnet.
This PR also removes circleci `resource_class` usages.

Reduced circleci usage

---

.circleci/config.yml
.circleci/src/jobs/job-unit-tests-coverage.yml

We recently removed the xlarge resource class from the CI's coverage job. This caused the job to fail with error 147, which means out of memory. A setting of large seems to work.

Fixes coverage on CI on hardhat refactor

---

.circleci/config.yml
.circleci/src/workflows/workflow-develop.yml

Atm, coverage is not working with buidler. We're working on a fix in the hardhat migration, but it may take a while for that to be ready. Until then, we should disable it so that we don't have to sudo merge PRs.

Disable coverage in ci until its fixed

---

package.json
publish/index.js
publish/src/Deployer.js
publish/src/commands/connect-bridge.js
publish/src/commands/deploy-ovm-pair.js
publish/src/commands/deploy.js

Assuming that docker is used to start a local L1 chain and a local L2 chain using https://github.com/ethereum-optimism/optimism-integration, this PR adds a `deploy-ovm-pair` command that deploys and connects a pair of instances to be used for local production tests.
The PR also introduces OVM safety checking in the deployment process, to ensure that no dangerous `5b` or `JUMPDEST` opcodes exist in appended deployment constructor parameters.
Another interesting addition of the PR, is the ability for the deployment script to split addresses being imported in the AddressResolver into chunks. This was needed for OVM to avoid that call to exceed the block limit.
To try the script out:
1. `git clone git@github.com:ethereum-optimism/optimism-integration.git`
2. `cd optimism-integration`
3. …

Adds a command that deploys an OVM pair of instances on local chains

---

contracts/DebtCache.sol
contracts/ExchangeRates.sol
contracts/Exchanger.sol
contracts/FeePool.sol
contracts/Issuer.sol
contracts/Liquidations.sol
contracts/MintableSynthetix.sol
contracts/MultiCollateralSynth.sol
contracts/PurgeableSynth.sol
contracts/SynthetixBridgeToBase.sol
contracts/SynthetixBridgeToOptimism.sol

As far as I know, naming a return variable and using the return statement does not have unwanted effects. I've also verified this in Remix.
However, I believe that the code is semantically incorrect like this, and deviations between what's written and what's intended should always be avoided.

Always return named parameter for resolverAddressesRequired()

---

publish/src/commands/deploy-ovm-pair.js

Adds CLI options for specifying the L1 and L2 providers

deploy: ovm-pair cli options

---

package.json

Should fix `the authenticity of host 'github.com' can't be established` error on CircleCI.
npm docs also suggest to use url without `git+` prefix:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository

fix: circleci github auth issue (repository.url)

---

.circleci/config.yml
.circleci/src/jobs/job-prod-diff-tests.yml
.circleci/src/jobs/job-prod-tests.yml
.circleci/src/jobs/job-unit-tests-gas-report.yml
package.json

Codechecks SSH issue seems to be related to `npx`. Switching to `npm run` should fix this issue and make failing pipelines on `develop` green. In the meantime I'm continuing to debug the issue with CircleCI support team in #1125.

ci: fix failing codechecks on CI

---

publish/deployed/kovan-ovm/params.json
publish/src/commands/deploy.js
test/publish/index.js

Although we recently addressed the setting in of `waitingPeriodSecs` in the deploy script, it still not behaving as expected. Them problem is that, in Optimism configurations, we actually want the value to be zero. The deploy script considers something "unset" when it is zero. Thus, if it finds `waitingPeriodSecs` to be zero, it will set it back to 300s when redeploying to an ovm network, effectively turning fee reclamation back on!
Since the deploy script would require a complete redesign regarding setting parameters to fix this, the modification proposed here merely always considers whatever is set to be valid when the value specified in params.json is zero, and maintains the old behavior otherwise.

Fix deploy script overriding waitingPeriodSecs from zero

---

publish/src/commands/deploy.js

This was causing prod tests to fail as MAX_DEBT was still set to 50m in `index.js` and prod tests were reverting the fork values to `50m` from `65m`.

Ensuring collateral defaults change only when non-zero

---

test/deployments/index.js

The test assumed that if a contract had the public property `resolver` that it was a `MixinResolver`.

Fix for validate-deployments for the virtual synth mastercopy

---

contracts/SynthetixBridgeToBase.sol
contracts/SynthetixBridgeToOptimism.sol
contracts/interfaces/ISynthetixBridgeToBase.sol
test/contracts/SynthetixBridgeToBase.unit.js
test/contracts/SynthetixBridgeToOptimism.unit.js
test/optimism/depositAndMigrateEscrow.test.js
test/optimism/index.js
test/optimism/rewards.test.js

- `MintedSecondaryRewards` => `RewardDepositInitiated` and emits the msg sender.
- `RewardDepositInitiated` now emits also the msg sender.
- `finalizeRewardDeposit()` uses an extra argument (from denoting the msg sender on L1)

Rename bridge emitted to be consistent to Optimism's interfaces

---

.solcover.js
contracts/BridgeMigrator.sol
contracts/SynthetixBridgeEscrow.sol
contracts/interfaces/ISynthetixBridgeEscrow.sol
publish/deployed/kovan/deployment.json
publish/index.js
publish/src/commands/migrate-bridge.js

Since the migration of SNX from the existing SynthetixBridgeToOptimism (v1) to the new SynthetixBridgeEscrow (v2) is a delicate operation, this PR proposes a way to do so with a script and a migration contract that will perform and validate the migration in a single atomic transaction, thus completely failing or succeeding.

Implements a contract for safer bridge migration

---

.circleci/config.yml
.circleci/src/jobs/job-prod-tests-ovm.yml
test/prod/EtherCollateral.prod.js

* Disables Optimism prod tests until the ops tool is fixed
* Fixes EtherCollateral prod tests to not use the Depot anymore

Fixes Ci tests

---

test/contracts/EtherWrapper.js

Fixes tests broken by this change: https://github.com/Synthetixio/synthetix/commit/8bd0057830284a6c4f3b855b7e8a0360c9e36e38

Fixing EthWrapper tests by restoring default rates in test setup

---

.circleci/config.yml
.circleci/src/jobs/job-unit-tests.yml
hardhat.config.js
hardhat/tasks/task-test.js

The objective of this PR is to improve the performance of running the unit tests both locally and on the CI.
Mocha versions starting from [`8.0.0`](https://github.com/mochajs/mocha/releases/tag/v8.0.0) adds a native parallelization feature using workers. This is implemented [here](https://github.com/Synthetixio/synthetix/pull/1233/commits/aab9cd6ac6eb990403e36307c1f2f06a8562bce5) making hardhat to use the locally installed version of mocha which is newer and has the feature. 
It can be used with:
```bash
npm run test -- --parallel
```
**_For the future_**, when Mocha gets updated on hardhat (https://github.com/nomiclabs/hardhat/pull/1429) we should be able to just delete the subtask override.
**_Register mocha plugin:_** In this case, instead of using the mocha register plugin as …

Add unit tests parallelization

---

.circleci/config.yml
.circleci/src/jobs/job-unit-tests-coverage-report.yml
.circleci/src/jobs/job-unit-tests-coverage.yml
.circleci/src/snippets/require-unit-tests-coverage.yml
.circleci/src/workflows/workflow-all.yml

This is a follow up on [unit tests parallelization PR](https://github.com/Synthetixio/synthetix/pull/1272), implementing the same strategy for CI, but including coverage reports.
After implementing parallelization the job improved run time from [`33m`](https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7125/workflows/f239da92-a9d6-4bd7-9c5b-afd59c487b6f/jobs/65393) to [`10m`](https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7129/workflows/0ab7ca13-3675-4680-b7af-1c4725380923/jobs/65456)

Add coverage parallelization

---

contracts/BaseSynthetix.sol
contracts/Exchanger.sol
contracts/PurgeableSynth.sol
contracts/Synth.sol
contracts/Synthetix.sol
contracts/interfaces/IExchanger.sol
contracts/interfaces/ISynthetix.sol
test/contracts/BaseSynthetix.js
test/contracts/Exchanger.spec.js
test/contracts/ExchangerWithVirtualSynth.unit.js
test/contracts/Synthetix.js
test/contracts/TradingRewards.spec.js

#1285 caused `Exchanger.sol` to be oversize on OVM during deployment. 
This PR overhauls `Exchanger.sol` by deduping the restricted `exchange*()` functions into one mighty handler 💪🏼 .

Refactoring of Exchanger.sol to reduce size on OVM

---

contracts/Exchanger.sol

As pointed out in the audit, an additional check for `rewardsAddress != address(0)` wasn't required. While there, I noticed more cleanup was possible.

Audit feedback and spring cleaning

---

contracts/MintableSynthetix.sol
hardhat/tasks/task-test-integration-l2.js
package-lock.json
test/integration/behaviors/erc20.behavior.js
test/integration/dual/withdraw.integration.js
test/integration/dual/withdrawTo.integration.js
test/integration/utils/balances.js
test/integration/utils/bootstrap.js
test/integration/utils/bridge.js
test/integration/utils/rates.js

Previously, to ensure that the owner has SNX in a standalone L2 instance (remember there is no initial supply in L2), the deploy was forced to ignore deployment parameters, which is where 0 issuance was set.
This PR removes that, because we actually need deployment parameters for other things, not just issuance. Instead, it tries different methods to get SNX for the owner in tests. In the particular standalone L2 case, it "hacks" the minting process and prints SNX for the user in `balances.js::_getSNXForOwnerOnL2ByHackMinting()`
https://github.com/Synthetixio/synthetix/pull/1303/files#diff-f4eeff274fd8a21e1f7fae9052616e130c9c52e7642d45ac742ba310881ad1caR55

Better way to get SNX in integration tests

---

.circleci/config.yml
.circleci/src/jobs/job-fork-tests.yml
.circleci/src/jobs/job-integration-tests.yml
.circleci/src/jobs/job-prod-tests-ovm.yml
.circleci/src/workflows/workflow-all.yml
hardhat/tasks/task-test-integration-l1.js
package-lock.json
test/integration/behaviors/stake.behavior.js
test/integration/utils/bootstrap.js
test/integration/utils/contracts.js
test/integration/utils/deploy.js
test/integration/utils/users.js

This PR introduces the ability to simulate an L1 deploy and run integration tests against it, with:
1. `npm run fork`
2. `npx hardhat test:integration:l1 --fork --compile --deploy`
Which runs tests in `test/integration/l1` against a fork of mainnet. The PR also introduces a CI job for the test. Note that not specifying `--deploy` will simply run the integration tests against the current mainnet deployment.
PS: This also fixes a problem with the old ovm prod tests.

Introduces forking via integration tests

---

.circleci/config.yml
.circleci/src/workflows/workflow-all.yml

Simply disables the tests, but doesn't delete the files because we need them while we finish porting everything to the new integration tests format.

Disables prod tests from CI

---

.circleci/config.yml
.circleci/src/jobs/job-integration-tests.yml
.gitignore
hardhat/tasks/task-test-integration-dual.js
hardhat/tasks/task-test-integration-l1.js
hardhat/tasks/task-test-integration-l2.js
package-lock.json
publish/src/commands/build.js
test/integration/utils/deploy.js

This allows integration tests to reuse compilation artifacts in `./build` and `./build-ovm` folders, greatly increasing the flexibility of integration tests.
For example, previously you could run `npx hardhat test:integration:l1 --compile --deploy`, and then re-run without `--compile` or even without `--deploy`.
Then you could do the same with the l2 tests. However, if you went back to l1, or dual, you'd be forced to compile again every time.
Holding the artifacts in different folders, allows you to only have to compile when contracts change, and not when switching between l1, l2, or dual integration tests.

Enables separate folder compilation for integration tests

---

hardhat/tasks/task-ops.js
index.js
publish/src/Deployer.js
publish/src/commands/connect-bridge.js
publish/src/commands/deploy/index.js
publish/src/commands/deploy/perform-safety-checks.js
publish/src/commands/deploy/rebuild-resolver-caches.js
publish/src/util.js
test/integration/utils/deploy.js

Allows us to run integration tests and deploy with the latest Optimism ops tool, which begins to use the new L2 gas rules:
https://www.notion.so/How-to-pay-Fees-in-Optimistic-Ethereum-f706f4e5b13e460fa5671af48ce9a695
This is achieved by:
* Not specifying a gas limit and using estimateGas in web3 instead.
* Removing the default ops commit in `npx hardhat ops`
* Removing web3 in `connect-bridge.js` in favour of ethers, because ethers auto estimates gas.

Unpins the usage of the Optimism ops tool and starts managing L2 gas

---

package-lock.json
publish/src/commands/deploy/index.js
publish/src/commands/deploy/system-and-parameter-check.js
publish/src/commands/nominate.js
test/integration/behaviors/nominate.behavior.js
test/integration/l1/Owned.l1.integration.js
test/integration/l2/Owned.l2.integration.js
test/integration/utils/deploy.js

Web3 is easy to remove from admin scripts like nominate.js. This PR adds an integration test for it, then replaces usage of web3 to ethers.

Removes web3 from nominate script

---

output.txt
output_new.txt
publish/src/commands/extract-staking-balances.js

Tested comparing output and owedBalances.csv result file before and after removing web3.
Command used to test: `node publish extract-staking-balances -n mainnet -s iETH`
There's a slight difference in both, the output and resulting file on the precision of the token price: **774** (original) vs **774.0** (modified)
I can apply a precision's reduction at the moment of display the values if that is needed, but can have an impact on "prices" with decimals
Old File:
```
Address,Staked Balance,Owed sUSD,Readable Staked Balance,Readable Owed sUSD
0x3787D321e3eCe1E4ca7D7449D49A4Fb5F85dc447,25129829656148489,19392136689397353694,0.025129829656148489,19.392136689397353694
0x7e7D26Ad3d4E00b4E9bD2e85A794e200Ceb405AA,280312637330344164,216311095349805323787,0.280312637330344164,216.311095349805323787 …
```

Removed web3 from extract-staking-balances

---

.circleci/config.yml
.circleci/src/jobs/job-integration-tests.yml
hardhat/tasks/task-ops.js

Add a cache on circleci to save the built `./optimism` folder. This cache is going to have the default CircleCI expiration of 15 days.
If the cache doesn't exists, it will download and build the optimism services, and will take 8mins~:
* https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7531/workflows/4ebd7a13-58b9-41e0-9e56-7663632f8eb2/jobs/71260
But, after having the cache enabled, we save that build step:
* https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7533/workflows/29f73703-5923-456c-998d-3e0fb81332e4/jobs/71281

Add caching of docker layers on integration tests job

---

.circleci/config.yml
.circleci/src/jobs/job-validate-deployments.yml

Closes https://github.com/Synthetixio/synthetix-pm/issues/166
Avoid to execute the `job-validate-deployments` job on every PR, and instead execute it when `publish/deployed/mainnet/deployment.json` file changes.
__Notice:__ This PR takes into account that changes to `publish/deployed/mainnet/deployment.json` are done only through the `develop` branch, because if we make a PR to directly `master` to modify that file, this filter would not work correctly.
For testing purposes I created a fake change on the `deployments.json` file, and it correctly executed the tests:
* https://app.circleci.com/pipelines/github/Synthetixio/synthetix/7545/workflows/b11df7d2-6840-4737-bf62-61ba2e1cb3b5/jobs/71437
And, after I restored the `deployments.json` file, the check worked correctly:
* …

Only execute job-validate-deployments if mainnet/deployment.json file changes

---

publish/src/commands/import-fee-periods.js
publish/src/commands/purge-synths.js
publish/src/util.js

Another step in the web3 removal process. 
It removes web3 from import-fee-period script and adds the capability of stringify BigNumber from ethers in a human readable format. 
Also small additional fix: remove non-deleted development log from purge-synths

Remove web3 from remove-fee-periods

---

publish/src/commands/remove-synths.js

Part of the web3 removal effort. This time remove-synths.js
Also adding the script the ability to use a fork and dry-run

Remove web3 from remove-synths

---

publish/src/commands/connect-bridge.js
publish/src/commands/import-fee-periods.js
publish/src/commands/migrate-binary-option-markets.js
publish/src/commands/nominate.js
publish/src/commands/owner.js
publish/src/commands/purge-synths.js
publish/src/commands/remove-synths.js
publish/src/commands/settle.js

Propagate fix applied in [PR-1354](https://github.com/Synthetixio/synthetix/pull/1354/files) to the rest of the modified scripts as part of the web3 removal. Also unifying the way to get the wallet with or without privateKey and ensuring wallet.address is always present.

Unify wallet creation and ensure .address is always present

---

publish/src/commands/deploy/generate-solidity-output.js
publish/src/commands/deploy/index.js
publish/src/util.js

The logic for adding to `runSteps` was overly complicated from previous versions and not properly refactored.

Simplify conditional logic of generate solidity

---

.circleci/config.yml
.circleci/src/jobs/job-integration-tests.yml
.circleci/src/snippets/job-header-machine.yml
.circleci/src/workflows/workflow-all.yml
test/integration/utils/bootstrap.js

Change machine used in CI to upgrade docker to 20.10.x.
Re-enable L2 and dual tests on integration tests.

Re-enable ops-tool in CI

---

hardhat/tasks/task-interact.js

Change hh task to use DEPLOY_PRIVATE_KEY or TESTNET_PRIVATE_KEY depending on the targetNetwork instead of just using PRIVATE_KEY

Add support to use Testnet or Deploy privateKey to CLI

---

hardhat/tasks/task-ops.js

This PR fixes the issue found by Liam [Issue-1403](https://github.com/Synthetixio/synthetix/issues/1403) where ops is not detecting correctly if ops is running when other docker-compose based image is running.

Fix issue 1403 - npx hardhat ops doesn't detect if ops node running correctly

---

publish/index.js
publish/src/commands/relayed-nominate.js

Adds the command `relayed-nominate` to be able to set a new owner on contracts located at L2 using a relay from L1. 
E.g.:
```bash
node publish relayed-nominate --l1-network=kovan --l1-provider-url=http://127.0.0.1:8545 --l2-network=kovan-ovm --l2-provider-url=http://127.0.0.1:8545 --new-owner=0x000...
```

Add relayed-nominate command to governance-bridge branch

---

contracts/OwnerRelayOnOptimism.sol
test/contracts/OwnerRelayOnOptimism.js

Adds a `OwnerRelayOnOptimism.acceptOwnershipOnBatch` function to facilitate the action on many contracts.

Add ability to accept ownership on an array of contracts in the owner relay

---

.circleci/config.yml
.circleci/src/jobs/job-fork-tests.yml
bin.js
index.js
package-lock.json
package.json
publish/index.js
publish/releases.json
publish/src/commands/finalize-release.js
publish/src/commands/release.js
publish/src/commands/versions-update.js

In order to prevent confusion of adding and selecting releases, this PR preps a handful of upcoming releases. It also adds entries for each release in both L1 and OVM. 
The trick is ensuring that the release is marked as `true` once complete. So when a release is kicked off, either it starts `node publish release .... --layer ovm` or `--layer base` or `--layer both`.
1. Added `finalize-release` command to be run by releases pipeline (which both updates the version files and the releases.json) (the updating of the version files [was previously run by the releases pipeline](https://github.com/Synthetixio/releases/blob/master/.circleci/config.yml#L163) so this will be managed here going forward)
1. Updated the `releases` binary command to a) use `--unreleased` and b) use `--with-sources` and …

Adding the next few releases

---

publish/src/commands/connect-bridge.js
publish/src/commands/nominate.js
publish/src/commands/owner.js

Nominate and Owner scripts fails if any contract in config.json is not deployed (or present in deployment.json).
This PR adds a check on that condition and show a warning while trying to Nominate or Accept ownership.

Fix nominate and owner scripts

---

contracts/StakingRewards.sol
test/contracts/StakingRewards.js

Remove `updatePeriodFinish` owner function that had issue when the input timestamp was not validated and could result in the contract unable to update staker's rewards and withdraw their staked tokens.  
Owner only function should validate the timestamp input to be > block.timestamp. 
Remove function as required only for stopping reward emission on iETH and iBTC staking rewards which are no longer used.

Update stakingRewards to remove updatePeriodFinish

---

test/contracts/OwnerRelayOnOptimism.js

This PR removes `triggerSendMessage()` from  `OwnerRelayOnOptimism.js` as it complicates the code without being needed.
Since smock gives us the possibility to use the contract itself as the `msg.sender` we can simplify the tests without having to simulate all the `sendMessage` complexity of the sequencer.
Similarly to `triggerSendMessage()`,  `finalizeRelay() `is being used for both `finalizeRelay` and `finalizeRelayBatch` functionality

OwnerRelayOnOptimism unit test simplification

---

contracts/FuturesMarket.sol
contracts/FuturesMarketData.sol
contracts/MixinFuturesMarketSettings.sol
contracts/interfaces/IFuturesMarket.sol
test/contracts/FuturesMarket.js
test/contracts/FuturesMarketData.js

Does the following:
* Adds a function `accessibleMargin` that reports the amount of margin a user can actually withdraw given their current position.
* Updates `withdrawAllMargin` to withdraw this quantity.
* Fixes a bug in `transferMargin`, where the minimum initial margin check and some other pieces were not properly respecting short positions.

Futures accessible margin

---

contracts/Exchanger.sol
publish/releases.json
test/contracts/DebtCache.js
test/contracts/Exchanger.spec.js
test/contracts/Issuer.js

While `settle()` is smart enough to ignore any synth that is no longer in the system with a rate (see [this line](https://github.com/Synthetixio/synthetix/blob/master/contracts/Exchanger.sol#L225)) - and simply removes the entry in this case - there was an issue with `DebtCache` reverting. Thus, this change to 174 ensures that even after deprecation, if a user has unsettled exchanges into the synth being removed, settling them at a later date won't revert.
> Note: one requirement of this is that the aggregator for the synth is removed from `ExchangeRates` - which needs to be done during deprecation
Another way to solve this would be to guarantee all exchanges into the synth were settled prior to removing it, but this is an onerous task that would cost a lot of gas to process and even a …

SIP-174 Fix for settlements to not cached removed synths

---

contracts/Exchanger.sol
contracts/ExchangerWithVirtualSynth.sol
contracts/TradingRewards.sol
contracts/VirtualSynth.sol
contracts/test-helpers/FakeTradingRewards.sol

This is a cleanup of the contract imports so that multiple definitions of `IERC20` - both internally and via Open Zeppelin, don't start conflicting with each other at compile time (msg: `DeclarationError: Identifier already declared.`). This started appearing in the #1493 PR as the migration needed to import both `Issuer` and `Exchanger` which led to `ERC20` being imported, along with IERC20 from Open Zeppelin, and then clashed with other imports of the internal `IERC20`.
The solution was a) to remove all references to `VirtualSynth` from `Exchanger` in the first place, relying instead on the interface, as the minimal proxy solution allows for this; then b) remove `IERC20` imported into  VirtualSynth, relying on the OZ one.

Fixes for imports to prevent issues with IERC20

---

publish/src/commands/deploy/get-deploy-parameter-factory.js

This PR introduces a minor addition to `get-deploy-parameter-factory.js` so it can output the value of an overridden parameter of type `Object`.

Print deploy param object value

---

hardhat/tasks/task-interact.js

This allows the interact task to run at a specified [block tag](https://docs.ethers.io/v5/api/providers/types/#providers-BlockTag) for easier troubleshooting. For example, `npx hardhat interact --block-tag 13289452`.
Happy to make improvements prior to merge. Thanks!

Adds block tag parameter to interact task

---

contracts/CollateralManager.sol
publish/src/commands/deploy/get-deploy-parameter-factory.js
test/contracts/CollateralManager.js

This PR fixes an issue where opening a loan may hit the gas limit on L2 since `CollateralManager.exceedsDebtLimit` calls `totalLong` and `totalShort` which iterate through both long and short synth arrays.
- Added the `totalLongAndShort` function so we can do just one `SLOAD` per fnc call rather than doing one for each synth in a loop.
- Reporting ~1M gas savings

Refactor exceedsDebtLimit check

---

.github/workflows/codeql.yml

Added CodeQL integration, more details:
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql
- https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/triaging-code-scanning-alerts-in-pull-requests
- https://codeql.github.com/
It's already used across other Synthetix repositories if applicable.

ci: add codeql integration

---

publish/src/commands/finalize-release.js

- Fixes issue whereby a finalized release (in the release pipeline) does not actually mark the SIPs as released for the given `layer`
- Also fixes bug whereby releasing with version `-ovm` was being incorrectly skipped.

Fixing releases to also mark SIPs as released

---

publish/src/commands/deploy/get-deploy-parameter-factory.js
publish/src/commands/deploy/index.js

Removed the need to take action and confirm the values declared in `params.json` during the deployment process. It will just print a warning message now instead.

Fix param spam during deployment

---

contracts/FuturesMarket.sol
test/contracts/FuturesMarket.js

Fixing missing events data in `PositionModified` events.
This would make both onchain events investigation easier, and provide better data to UI.

add missing data in position modified events

---

publish/deployed/mainnet/feeds.json
publish/src/commands/deploy/configure-standalone-price-feeds.js

Basically this ensures that during future deploys of `ExchangeRates`, the feeds required for SCPP-139 will be saved to the contract storage

Ensuring SCCP-139 feeds are persisted to future ExchangeRates contracts

---

contracts/ExchangeRatesWithDexPricing.sol
contracts/SystemSettings.sol
contracts/interfaces/IDexPriceAggregator.sol
test/contracts/ExchangeRates.js
test/contracts/Exchanger.spec.js
test/contracts/SystemSettings.js

This PR addresses several minor issues in https://github.com/Synthetixio/synthetix/pull/1127 contract changes:
- Not using safemath for price and amount calculations in `ExchangeRatesWithDexPricing`
- Allowing setting dex oracle to zero address in `SystemSettings`
- Not checking dex oracle returned price to at least not be 0 in `effectiveAtomicValueAndRates`
- Not having comments about the the dex oracle `IDexPriceAggregator`: impelementation source, refernce interface source.
This PR also fixes a few issues with tests in that PR:
- Tests for `exchangeAtomically` not being correctly set up to trigger volatility checks (no configurtion for the check which causes the check to be skipped comletely). Which makes the test skip an important part of functionality it's testing, and also makes gas …

Sip 120 minor issues

---

contracts/FuturesMarket.sol
contracts/FuturesMarketData.sol
contracts/FuturesMarketSettings.sol
contracts/MixinFuturesMarketSettings.sol
contracts/interfaces/IFuturesMarket.sol
contracts/interfaces/IFuturesMarketSettings.sol
index.js
publish/deployed/kovan-ovm-futures/deployment.json
publish/src/commands/deploy/configure-futures.js
test/contracts/FuturesMarket.js
test/contracts/FuturesMarketData.js
test/contracts/FuturesMarketSettings.js
test/contracts/setup.js
test/utils/index.js

Updates the futures liquidation related logic for the first two items of https://github.com/synthetixio/issues/issues/352:
1. Proportional liquidation fee - to incentivise liquidations of larger positions first. Tentatively set to 35 bps.
2. Proportional liquidation margin buffer - to prevent negative margin liquidation, and to allow proportional fee to be paid to the fee pool. Tentatively set at 25 bps. If this buffer will not be needed in practice for safety (or for fees), the value can be set to 0 in the future.
These two values now allow controlling the proportional liquidation margin, and the allocation of that margin upon liquidation to the liquidator and fee pool. 
Other important changes in this PR:
- Adding the parameters to `FuturesMarketSettings`: `liquidationFeeBPs` and …

Futures liquidation fee update

---

contracts/WrapperFactory.sol
contracts/test-helpers/MockSynth.sol
publish/releases.json
publish/src/commands/deploy/index.js
publish/src/commands/deploy/rebuild-resolver-caches.js
test/contracts/WrapperFactory.js
test/contracts/setup.js

`WrapperFactory` is submitting a second `recordFeePaid` call. We need to fund the fee pool the missing $257k, and update the fee pool afterwards to ensure correct accounting.
The error was covered by unit tests prior to the discovery of this bug, but it lead to diverging functionality on-chain because the Synth used for `sUSD` is a `MockSynth`, not the actual `Synth`. This lead to coming to the wrong conclusion that having the additional `recordFeePaid()` was actually necessary.
To correct the unit tests, `MockSynth` was updated to match the functieonality of the `Synth` class with regards to the Fee period record fee paid.
This bug affects both L1 and L2, but only L2 will require funding or fee pool correction.

fix duplicate fee reporting on WrapperFactory

---

contracts/BaseSynthetix.sol
contracts/Synthetix.sol
publish/releases.json
test/contracts/BaseSynthetix.js

The `liquidateDelinquentAccount` logic from `Issuer.sol` was indeed added to OVM during the [Menkalinan release](https://blog.synthetix.io/the-menkalinan-release/) however it can only be invoked via `Synthetix` which was not updated during that release.
This addresses that by moving the logic to the base class which both layers use.

SIP-194 Fix Liquidations on L2

---

contracts/FuturesMarketBase.sol
contracts/FuturesMarketData.sol
contracts/MixinFuturesNextPriceOrders.sol
contracts/interfaces/IFuturesMarket.sol
contracts/interfaces/IFuturesMarketBaseTypes.sol

This reduces the stored variables sizes for some gas savings. 
Main savings are for the most expensive methods - `modifyPosition` and `executeNextPriceOrder` of around 80K gas:
- `modifyPosition` : 420K gas -> 340K gas
- `executeNextPriceOrder`: 470K gas -> 390K gas
On OVM this will translate to minor savings at this time because L2 gas is not the main cost, but given possible future added complexity and rising prices, it's still wise to take advantage of the easy savings. 
In terms of savings on calldata (for the L1 part of cost) - it's already minimal with most methods accepting at most one argument.
-----------------
Full tables (third numeric:
```
|  Contract                     ·  Method                            ·  Min         ·  Max        ·  Avg              ·  # calls      · …
```

reduce storage variables sizes for gas savings

---

hardhat/util/collectContractBytecodes.js
publish/src/contract-size.js

This meant that `job-compile` could fail oversize even though technically the contract was not too big to deploy. 
Before in `develop`
| `npx hardhat compile --optimizer --showsize` | `node publish build --show-size` |
| - | - |
| ![image](https://user-images.githubusercontent.com/799038/145333871-6c92d1e9-01c2-49cd-9529-dea3b0bce431.png) | 
|
This PR
| `npx hardhat compile --optimizer --showsize` | `node publish build --show-size` |
| - | - |
| ![image](https://user-images.githubusercontent.com/799038/145335852-51d4a364-9e57-4c62-a64a-1209ceb3c663.png) | ![image](https://user-images.githubusercontent.com/799038/145336402-ec3ea7eb-db38-42aa-ad16-61b3765fd85e.png) |

Ensuring job-compile size check matches build command

---

test/integration/behaviors/stake.behavior.js
test/integration/l1/Liquidations.l1.integrations.js
test/integration/l2/Liquidations.l2.integration.js
test/integration/utils/rates.js

- increase stake behaviour SNX mint
- update setRate to deploy mockAggregator

Fix CI test

---

test/integration/behaviors/liquidations.behavior.js

the new conditions for this test will more accurately detect the expected condition and should be much more resistant to failure

fix liquidations fork test fail

---

publish/index.js
publish/src/commands/deploy-migration.js

this should make releases a little easier and make it easier to utilize the migration script functionality of the deployer.

migration script helper allows deployment and staging of migration script call

---

publish/deployed/kovan-ovm/deployment.json
publish/deployed/mainnet-ovm/deployment.json

Remove old `RewardEscrow` deployment artifacts from mainnet-ovm and kovan-ovm `deployment.json` files

Remove legacy deployments

---

publish/deployed/kovan-ovm/feeds.json

The ChainLink OCR proxies are not yet ready on `kovan-ovm`, but the aggregators are up running smoothly.  We can use these in the interim until the proxies are deployed.
⚠️ *Note these are aggregator contracts -- **not** the proxies.*

Update kovan-ovm feeds with new aggregator contracts

---

publish/deployed/kovan-ovm/feeds.json

New `kovan-ovm` OCR proxy addresses from CL roger:
```
BTC/USD 0xd9BdB42229F1aefe47Cdf028408272686445D3ff
ETH/USD 0x7f8847242a530E809E17bF2DA5D2f9d2c4A43261
LINK/USD 0x4e5A8fe9d533dec45C7CB57D548B049785BA9861
SNX/USD 0x38D2f492B4Ef886E71D111c592c9338374e1bd8d
```

Update kovan ovm feeds with latest OCR proxies

---

contracts/BaseMigration.sol
publish/src/commands/deploy-migration.js
publish/src/commands/deploy/generate-solidity-output.js

also the owner can now run migration, instead of the deployer, which is way better for getting stuff done
going to also add verification on etherscan

update migration script to also stage nominations

---

.circleci/config.yml
.circleci/src/jobs/job-fork-tests-ovm.yml
.circleci/src/jobs/job-fork-tests.yml

Compilation is required for a few of the fork tests, regardless of whether or not new files are added:
```
1) Liquidations (L2)
liquidating
"before all" hook: exchange rate is set for "cannot be liquidated at this point":
TypeError: Cannot read properties of undefined (reading 'MockAggregatorV2V3')
at createMockAggregatorFactory (test/utils/index.js:539:15)
at addAggregatorAndSetRate (test/integration/utils/rates.js:34:38)
at Context.<anonymous> (test/integration/behaviors/liquidations.behavior.js:49:10)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
and
```
2) WrapperFactory integration tests (L2)
"before all" hook in "WrapperFactory integration tests (L2)":
TypeError: Cannot read properties of undefined (reading 'Wrapper')
at Context.<anonymous> …
```

Ensuring fork tests do compile

---

contracts/ExchangeCircuitBreaker.sol
contracts/FuturesMarketBase.sol
contracts/MixinFuturesNextPriceOrders.sol
contracts/MixinFuturesViews.sol
contracts/interfaces/IFuturesMarketBaseTypes.sol
test/contracts/FuturesMarket.js
test/contracts/FuturesMarket.nextPrice.js
test/contracts/FuturesMarketData.js

Use dynamic fee during modifying positions actions in futures:
- Fee is applied to trades (modify position, close position, next price orders)
- Fee is not applied to liquidations (different fee structure)
Dynamic fee over max reverts modifying positions, but does not revert margin actions and liquidations.

Futures dynamic fee

---

contracts/Exchanger.sol
contracts/interfaces/IExchanger.sol
hardhat.config.js
hardhat/tasks/task-test.js
publish/releases.json
test/contracts/Exchanger.spec.js
test/contracts/setup.js
test/publish/index.js

The `exchangeRatesForExchange` function signature changed in the Alsephina release, this SIP proposes that the old function signature remains the same to prevent integrations that rely on the function from breaking.

SIP-209 Update feeRateForExchange function signature

---

contracts/FuturesMarket.sol
contracts/FuturesMarketBase.sol
contracts/FuturesMarketData.sol
contracts/FuturesMarketManager.sol
contracts/FuturesMarketSettings.sol
contracts/MixinFuturesMarketSettings.sol
contracts/MixinFuturesNextPriceOrders.sol
contracts/MixinFuturesViews.sol
contracts/interfaces/IFuturesMarket.sol
contracts/interfaces/IFuturesMarketSettings.sol
contracts/test-helpers/TestableFuturesMarket.sol
publish/deployed/kovan-ovm-futures/futures-markets.json
publish/deployed/local-ovm/futures-markets.json
publish/src/commands/deploy/configure-futures.js
publish/src/commands/deploy/deploy-futures.js
test/contracts/FuturesMarket.js
test/contracts/FuturesMarket.nextPrice.js
test/contracts/FuturesMarketData.js
test/contracts/FuturesMarketManager.js
test/contracts/FuturesMarketSettings.js
test/contracts/setup.js

https://github.com/synthetixio/issues/issues/414
- removing proxy related things (10%)
- removing unused functionality and moving things that are only used for test into the Testable contract, moving some things that are only used in MarketData views there. Checked that all methods used Kwenta code aren't touched.
- Refactoring the gazzillion getters in settings mixin into a single getter with a struct `config` and passing it around, ended up being worse
- Refactoring the getters used for external views into two structs (position details and market details) - was almost the same, but a bit larger.
Compiler errors relating to structs and ABIEncoderV2 issues. In some cases, the pragma needs to be added into an inheriting contract, but the compiler won't tell you this, and definitely won't …

Futures size reduction

---

contracts/FuturesMarketBase.sol
contracts/SystemStatus.sol
contracts/interfaces/ISystemStatus.sol
test/contracts/FuturesMarket.js
test/contracts/FuturesMarket.nextPrice.js
test/contracts/SystemStatus.js

This adds the ability to pause a single futures market. Previously the whole futures system was pausable, this allows to pause a specific market. The following circumstances may require this:
- Some problem with a particular market that needs requires pausing.
- Pausing due to trading hours of the corresponding underlying asset.
- Migration related activities.
Also added a test to ensure that it's possible to pause funding rate for the duration of the pause by setting max funding rate to 0 before/after pausing and resetting it to correct value before/after resumption.

Futures single market pausing

---

contracts/EmptyFuturesMarketManager.sol
contracts/Exchanger.sol
contracts/FuturesMarket.sol
contracts/FuturesMarketBase.sol
contracts/FuturesMarketData.sol
contracts/FuturesMarketManager.sol
contracts/FuturesMarketSettings.sol
contracts/MixinFuturesMarketSettings.sol
contracts/MixinFuturesNextPriceOrders.sol
contracts/MixinFuturesViews.sol
contracts/interfaces/IFuturesMarket.sol
contracts/interfaces/IFuturesMarketManager.sol
contracts/test-helpers/MockFuturesMarket.sol
contracts/test-helpers/TestableFuturesMarket.sol
publish/deployed/kovan-ovm-futures/futures-markets.json
publish/deployed/local-ovm/futures-markets.json
publish/src/commands/deploy/configure-futures.js
publish/src/commands/deploy/deploy-futures.js
test/contracts/DebtCache.js
test/contracts/FuturesMarket.js
test/contracts/FuturesMarket.nextPrice.js
test/contracts/FuturesMarketData.js
test/contracts/FuturesMarketManager.js
test/contracts/FuturesMarketSettings.js
test/contracts/setup.js

This allows market keys that are different from asset keys, which makes migration possible.

Futures support multiple markets for same asset

---

contracts/BaseDebtCache.sol
contracts/interfaces/IDebtCache.sol
publish/src/commands/deploy/import-excluded-debt.js
publish/src/commands/deploy/index.js
test/contracts/DebtCache.js

Adds the ability to import excluded debt entries which is needed for upgrading to new DebtCache instance.

Debtcache import excluded debt entries

---

contracts/EmptyFuturesMarketManager.sol
contracts/FuturesMarketManager.sol
contracts/OneNetAggregatorDebtRatio.sol
contracts/OneNetAggregatorIssuedSynths.sol
contracts/SynthetixBridgeToBase.sol
contracts/SynthetixBridgeToOptimism.sol
contracts/SystemStatus.sol

This PR updates the contracts that do not conform to the `bytes32 public constant CONTRACT_NAME` pattern.

Add CONTRACT_NAME constants

---

test/contracts/Exchanger.spec.js

There was an interaction between the changes in #1667 and #1749 which led to a unit test failure. With the PR for SIP-222, the relevant exchange fees were doubled, which resulted in a smaller amount of sETH being provided in the failing test.

Fix Exchanger Unit Tests

---

contracts/Exchanger.sol
contracts/ExchangerWithFeeRecAlternatives.sol
test/contracts/Exchanger.spec.js

`Exchanger.exchange` does not use the post-reclaim amount to calculate the amount of exchange for the
user trade. This leads to the user being left with more of their source token then they should
have had.
this PR resolves this problem by ensuring amounts used for exchange are
calculated for the amount after fee reclamation has occured. It also adds associated tests.
SIP to be assigned pending

SIP-236: fix exchange before reclaim risk

---

publish/deployed/kovan-ovm/feeds.json
publish/deployed/kovan-ovm/futures-markets.json

Futures summary views were broken because feeds were not added for AXS and LUNA.
Changes in config:
- add feed for AXS into feeds json
- remove LUNA from markets json
Changes on chain:
- add feed for AXS to rates contract
- remove LUNA market from futures manager

fix kovan futures: add axs feed, remove luna mkt

---

test/integration/behaviors/futures.behavior.js

Fork test failure caused by funding rate changing debt too fast for the tolerance in the test. The fix is to both move the reference value recording closer to the test value (by several transactions), and to increase the tolerance.

fix flaky futures fork test

---

.circleci/config.yml
.circleci/src/snippets/job-header-node.yml
.circleci/src/snippets/job-header-sec-tools.yml
.github/workflows/slither-analysis.yml

changes:
- use node@lts (16.15)
- fix failing pipeline (slither)
- improve caching to work cross-platform
- consider node version while creating cache dir

ci: use node@LTS(16.15)

---

bin.js

Adds a command to the bin.js to decode Gnosis multi-send payload.
Usage: ./bin.js decode-multi-send `MULTI SEND transactions(bytes)`
i.e.
```./bin.js decode-multi-send 0x008d203c458d536fe0f97e9f741bc231eac8cd91cf0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002425a3746e0000000000000000000000000000000000000000000189ae49790084000000000029c295b046a73cde593f21f63091b072d407e3f200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000064e54c1671000000000000000000000000000000000000000000000000000000000000000200000000000000000000000039ea01a0298c315d149a490e34b59dbf2ec7e48f000000000000000000000000000000000000000000009d78ea2fb0b518000000```
will result …

Add MultiSendDecode command to bin.js

---

publish/assets.json
publish/deployed/mainnet-ovm/feeds.json
publish/deployed/mainnet-ovm/futures-markets.json

Adding the configs for https://sips.synthetix.io/sips/sip-257/
Didn't add testnet feed and config, since it doesn't look like they exist yet.

adding debt-ratio futures market

---

contracts/PerpsEngineV2Base.sol
contracts/PerpsManagerV2.sol
contracts/PerpsManagerV2ConfigSettersMixin.sol
contracts/PerpsOrdersV2NextPriceMixin.sol
contracts/PerpsStorageV2.sol
test/contracts/PerpsEngineV2.js
test/contracts/PerpsManagerV2.configSetters.js
test/contracts/PerpsManagerV2.js
test/contracts/PerpsOrdersV2.nextPrice.js
test/contracts/PerpsStorageV2.js

Most require error messages are in sentence case.
This also removes trailing white spaces on some files. Rather than adding 20 suggestion comments in PR #1859, I did it all in one easy to approve/merge commit.

Make very minor copy changes to require err msgs

---

.circleci/config.yml
.circleci/src/jobs/job-fork-tests-ovm.yml
.circleci/src/jobs/job-fork-tests.yml
publish/deployed/local/config.json
publish/deployed/mainnet-ovm/feeds.json
publish/deployed/mainnet-ovm/futures-markets.json
publish/src/commands/deploy/import-addresses.js
publish/src/commands/deploy/index.js

fix not running fork tests or `job-test-deploy-script` in CI (but not exiting with error, thus having the illusion of successful tests).
Also removes the DebtRatio market (and feed) since new CircuitBreaker isn't able to support it.

fix not running fork tests

---

contracts/ImmutableReadProxy.sol
test/contracts/ReadProxy.js

Workaround for the DebtRatio arrgegator conflict with the new CricuitBreaker contract.
This adds an `ImmutableReadProxy` contract that is a unowned simplier variant of the `ReadProxy` contract. This contract will be deployed with the `DebtRatio` oracle aggregator as the target. This will enable forwarding all views via this contract, and prevent the address collision in the new CircuitBreaker.

DebtRatio aggregator <> CircuitBreaker workaround: add immutable read proxy

---

bin.js

show raw payload if not able to decode when not identifying the contract, i.e. for wrappers.

Fix bin.js for decode-relay-batch

---

contracts/PerpsV2Market.sol
contracts/PerpsV2MarketBase.sol
contracts/PerpsV2MarketDelayedOrders.sol
contracts/PerpsV2MarketDelayedOrdersBase.sol
contracts/PerpsV2MarketDelayedOrdersOffchain.sol
contracts/PerpsV2MarketProxyable.sol
contracts/PerpsV2MarketState.sol
contracts/PerpsV2MarketViews.sol
contracts/interfaces/IPerpsV2Market.sol
contracts/interfaces/IPerpsV2MarketBaseTypes.sol
contracts/interfaces/IPerpsV2MarketDelayedOrders.sol
contracts/interfaces/IPerpsV2MarketOffchainOrders.sol
contracts/interfaces/IPerpsV2MarketState.sol
contracts/interfaces/IPerpsV2MarketViews.sol
contracts/test-helpers/TestablePerpsV2Market.sol
test/contracts/PerpsV2Market.delayedOrder.js
test/contracts/PerpsV2Market.js
test/contracts/PerpsV2Market.offchainDelayedOrder.js
test/contracts/PerpsV2MarketData.js
test/contracts/PerpsV2MarketManager.js
test/integration/behaviors/perpsV2.behavior.js

As part of SIP 279, we introduce slippage protection as a complementary mechanism to premium/discount pricing. Slippage protection will allow users to specify a price percentage delta when making trades in both delayed orders and regular orders. The most impactful change involves a modification to two public interface methods modifyPosition and submitDelayedOrder.
```solidity
interface PerpsV2Market {
function modifyPosition(int sizeDelta, uint slippage);
function submitDelayedOrder(int sizeDelta, uint slippage, uint desiredTimeDelta);
function submitDelayedOrderWithTracking(int sizeDelta, uint slippage, uint desiredTimeDelta, bytes32 trackingCode);
function submitOffchainDelayedOrder(int sizeDelta, uint slippage);
function submitOffchainDelayedOrderWithTracking(
int sizeDelta,
uint …
```

SIP 279 Slippage Protection

---

contracts/PerpsV2Market.sol
contracts/PerpsV2MarketBase.sol
contracts/PerpsV2MarketDelayedOrders.sol
contracts/PerpsV2MarketDelayedOrdersBase.sol
contracts/PerpsV2MarketDelayedOrdersOffchain.sol
contracts/PerpsV2MarketProxyable.sol
contracts/PerpsV2MarketState.sol
contracts/PerpsV2MarketViews.sol
contracts/interfaces/IPerpsV2Market.sol
contracts/interfaces/IPerpsV2MarketBaseTypes.sol
contracts/interfaces/IPerpsV2MarketDelayedOrders.sol
contracts/interfaces/IPerpsV2MarketOffchainOrders.sol
contracts/interfaces/IPerpsV2MarketState.sol
contracts/test-helpers/TestablePerpsV2Market.sol
test/contracts/PerpsV2Market.delayedOrder.js
test/contracts/PerpsV2Market.js
test/contracts/PerpsV2Market.offchainDelayedOrder.js
test/contracts/PerpsV2MarketData.js
test/contracts/PerpsV2MarketManager.js
test/integration/behaviors/perpsV2.behavior.js

This PR introduces an additional premium to be paid by the trader when their position is liquidated. The period is _not_ paid to the keeper and given back to the stakers.
There are a few calculations that were changed, namely:
1. Liquidation price
2. Assertion in `canLiquidate`
3. Remaining margin on liquidation during liquidation
The liquidation premium is calculated as follows:
```
abs(size / skewScale) * 0.5
```
The adjustment to the liquidation price just subtracts the premium from their remaining margin:
```
int(position.lastPrice)
.add(int(liqMargin).sub(int(position.margin).sub(int(liqPremium))).divideDecimal(positionSize))
.sub(fundingPerUnit);
```
(2) and (3) use `_remainingLiquidatableMargin` to determine margin remaining after subtracting premium.

SIP 279 (cont.) Premiums applied on Liquidation

---

contracts/interfaces/IPerpsV2MarketConsolidated.sol
contracts/test-helpers/TestablePerpsV2MarketEmpty.sol

This PR introduces a consolidated interface and empty test contract that can be used as a base to connect to the proxied PerpsV2 markets. 
This can be used to connect any PerpsV2 market deployed on using the proxy address of the market address and the ABI of `TestablePerpsV2MarketEmpty` contract and use it as a simple contract.
i.e. if you want to connect to the ETH PerpsV2 market deployed in Goerli-optimism with ethers.js you can use:
```
const consolidatedPerpsV2MarketABI = [...] // the abi of the contract
const ethPerpsAddress = '0x111BAbcdd66b1B60A20152a2D3D06d36F8B5703c'
const contract = new ethers.Contract(ethPerpsAddress, consolidatedPerpsV2MarketABI, provider);
```

PerpsV2: Add helper interface and contract

---

contracts/MixinPerpsV2MarketSettings.sol
contracts/PerpsV2Market.sol
contracts/PerpsV2MarketBase.sol
contracts/PerpsV2MarketData.sol
contracts/PerpsV2MarketSettings.sol
contracts/PerpsV2MarketViews.sol
contracts/interfaces/IPerpsV2MarketSettings.sol
index.js
publish/src/commands/deploy/configure-perpsv2.js
test/contracts/PerpsV2Market.js
test/contracts/PerpsV2MarketData.js
test/contracts/PerpsV2MarketSettings.js
test/contracts/setup.js
test/integration/behaviors/perpsV2.behavior.js

This PR introduces a new parameter `maxKeeperFee` and use it to cap keeper liquidation fee

Add Cap to keeper liquidation fee

---

contracts/MixinPerpsV2MarketSettings.sol
contracts/PerpsV2MarketData.sol
contracts/PerpsV2MarketDelayedExecution.sol
contracts/PerpsV2MarketDelayedIntent.sol
contracts/frozen/FrozenMixinPerpsV2MarketSettings.sol
contracts/frozen/FrozenPerpsV2MarketBase.sol
contracts/interfaces/IPerpsV2MarketSettings.sol
test/contracts/PerpsV2Market.delayedOrder.js
test/contracts/PerpsV2Market.js
test/contracts/PerpsV2Market.offchainDelayedOrder.js
test/contracts/PerpsV2MarketData.js
test/contracts/PerpsV2MarketManager.js
test/contracts/PerpsV2MarketSettings.js
test/contracts/setup.js

This PR implements the SIP defined here: https://github.com/Synthetixio/SIPs/pull/1452 (https://sips.synthetix.io/sips/sip-2004/)
In summary, it removes the commitment fee charged upon submission and removes the ability to cancel an order during the confirmation window. This change also updates a variety of tests to reflect the new change and removes the overrideCommitFee SCCP param as it's now redundant.

Remove commitment fee charged during delayed order submissions

---

test/integration/behaviors/stake.behavior.js
test/integration/dual/debtMigration.integration.js
test/publish/.gitignore

*~~Bumped `foundry_locked_commit` to `1d9a34e` to fix anvil timeout~~
* Added empty `test.log` file to test/publish to fix file not found error in job-test-deploy
* `tail: cannot open 'test/publish/test.log' for reading: No such file or directory`
* Fix flaky `NOUNCE_EXPIRED` ethersjs errors in dual integration tests by adding snapshot before / restore after
* (https://github.com/ethers-io/ethers.js/issues/435)

Fix test deploy job and dual int tests

---

.circleci/config.yml
.circleci/src/jobs/job-fork-tests-ovm.yml
contracts/PerpsV2MarketBase.sol
hardhat/tasks/task-test-integration.js
publish/src/command-utils/perps-v2-utils.js
publish/src/commands/deploy/deploy-perpsv2.js
publish/src/commands/deploy/index.js
test/integration/behaviors/perpsV2.behavior.js
test/integration/utils/deploy.js

This PR fixes some CI tests. In order to do that it:
- propagates the `ignoreSafetyChecks` flag required by this deployment to the tests
- adds a missing address requirement (.sol minor change)
- rebuild caches for generic perpsV2 contracts once they are deployed 
- re-adds previous markets when `FuturesMarketManager` is updated (since the markets will be replaced asynchronous) (deployment fix on the fly)
- links the new state to the previous one by authorizing the new one as `associatedContract`

Fix CI-tests

---

publish/releases.json

* Adds missing debt migrator sources to the 237 entry in `releases.json`

Naos v2.84.4 post release sources update

---

publish/src/command-utils/perps-v2-utils.js
test/contracts/setup.js

Improve PerpsV2 deployment script by adding a comment in the migration contract with target information (`Add route contract.function`)
i.e.
```
// Add route to PerpsV2MarketBNBPERP.closePosition;
perpsv2proxybnbperp_i.addRoute(0xa126d601, 0xc7dCC0929881530d3386de51D9ffdD35B8009c6E, false);
// Add route to PerpsV2MarketBNBPERP.closePositionWithTracking;
perpsv2proxybnbperp_i.addRoute(0x5c8011c3, 0xc7dCC0929881530d3386de51D9ffdD35B8009c6E, false);
```

Add route information in migration contract

---

publish/deployed/goerli-ovm/perpsv2-markets.json
publish/deployed/mainnet-ovm/perpsv2-markets.json

- As per SCCP-2032 WLD should have a maxFundingVelocity of 36
- As per SIP-2030 USDT should be unpaused

SCCP-2032 / SIP-2030 Update

---

contracts/RewardsDistribution.sol
contracts/TradingRewards.sol

in the simplest possible way, fix a bug which prevents reward distribution from getting sent to L2 due to internal OOG gas logic in optimism contract (normally if you are OOG then the remaining code in RewardsDistribution would also fail, but optimism deliberately consumes an excessive amount of gas in a way that causes only the internal call to fail)
in accordance with [SIP-2036](https://sips.synthetix.io/sips/sip-2036/)
note: if you are wondering why I didnt just call the rewards distribution receiver contract normally and continue to be using hte low level call, the reason is im trying to keep changes to a minimal and this change basically ended up being a 1 line changes.

SIP-2036 fix reward distributor to bubble failures
